# This Python file uses the following encoding: utf-8

from music import MusicTrack, TrackFlag


cant_find_this = MusicTrack("cant_find_this", "cant_find_this.ogg")

mount_and_blade_title_screen = MusicTrack("mount_and_blade_title_screen", "mount_and_blade_title_screen.ogg")
mount_and_blade_title_screen.add_flag(TrackFlag.START_IMMEDIATELY)
mount_and_blade_title_screen.add_flag(TrackFlag.SIT_MAIN_TITLE)

ambushed_by_neutral = MusicTrack("ambushed_by_neutral", "ambushed_by_neutral.ogg")
ambushed_by_neutral.add_flag(TrackFlag.SIT_AMBUSHED)
ambushed_by_neutral.add_flag(TrackFlag.SIT_SIEGE)
ambushed_by_neutral.add_continue_flag(TrackFlag.SIT_FIGHT)
ambushed_by_neutral.add_continue_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)

ambushed_by_khergit = MusicTrack("ambushed_by_khergit", "ambushed_by_khergit.ogg")
ambushed_by_khergit.add_flag(TrackFlag.CULTURE_3)
ambushed_by_khergit.add_flag(TrackFlag.SIT_AMBUSHED)
ambushed_by_khergit.add_flag(TrackFlag.SIT_SIEGE)
ambushed_by_khergit.add_continue_flag(TrackFlag.CULTURE_1)
ambushed_by_khergit.add_continue_flag(TrackFlag.CULTURE_2)
ambushed_by_khergit.add_continue_flag(TrackFlag.CULTURE_4)
ambushed_by_khergit.add_continue_flag(TrackFlag.CULTURE_5)
ambushed_by_khergit.add_continue_flag(TrackFlag.CULTURE_6)
ambushed_by_khergit.add_continue_flag(TrackFlag.SIT_FIGHT)
ambushed_by_khergit.add_continue_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)

ambushed_by_nord = MusicTrack("ambushed_by_nord", "ambushed_by_nord.ogg")
ambushed_by_nord.add_flag(TrackFlag.CULTURE_4)
ambushed_by_nord.add_flag(TrackFlag.SIT_AMBUSHED)
ambushed_by_nord.add_flag(TrackFlag.SIT_SIEGE)
ambushed_by_nord.add_continue_flag(TrackFlag.CULTURE_1)
ambushed_by_nord.add_continue_flag(TrackFlag.CULTURE_2)
ambushed_by_nord.add_continue_flag(TrackFlag.CULTURE_3)
ambushed_by_nord.add_continue_flag(TrackFlag.CULTURE_5)
ambushed_by_nord.add_continue_flag(TrackFlag.CULTURE_6)
ambushed_by_nord.add_continue_flag(TrackFlag.SIT_FIGHT)
ambushed_by_nord.add_continue_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)

ambushed_by_rhodok = MusicTrack("ambushed_by_rhodok", "ambushed_by_rhodok.ogg")
ambushed_by_rhodok.add_flag(TrackFlag.CULTURE_5)
ambushed_by_rhodok.add_flag(TrackFlag.SIT_AMBUSHED)
ambushed_by_rhodok.add_flag(TrackFlag.SIT_SIEGE)
ambushed_by_rhodok.add_continue_flag(TrackFlag.CULTURE_1)
ambushed_by_rhodok.add_continue_flag(TrackFlag.CULTURE_2)
ambushed_by_rhodok.add_continue_flag(TrackFlag.CULTURE_3)
ambushed_by_rhodok.add_continue_flag(TrackFlag.CULTURE_4)
ambushed_by_rhodok.add_continue_flag(TrackFlag.CULTURE_6)
ambushed_by_rhodok.add_continue_flag(TrackFlag.SIT_FIGHT)
ambushed_by_rhodok.add_continue_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)

ambushed_by_swadian = MusicTrack("ambushed_by_swadian", "ambushed_by_swadian.ogg")
ambushed_by_swadian.add_flag(TrackFlag.CULTURE_1)
ambushed_by_swadian.add_flag(TrackFlag.SIT_AMBUSHED)
ambushed_by_swadian.add_flag(TrackFlag.SIT_SIEGE)
ambushed_by_swadian.add_continue_flag(TrackFlag.CULTURE_2)
ambushed_by_swadian.add_continue_flag(TrackFlag.CULTURE_3)
ambushed_by_swadian.add_continue_flag(TrackFlag.CULTURE_4)
ambushed_by_swadian.add_continue_flag(TrackFlag.CULTURE_5)
ambushed_by_swadian.add_continue_flag(TrackFlag.CULTURE_6)
ambushed_by_swadian.add_continue_flag(TrackFlag.SIT_FIGHT)
ambushed_by_swadian.add_continue_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)

ambushed_by_vaegir = MusicTrack("ambushed_by_vaegir", "ambushed_by_vaegir.ogg")
ambushed_by_vaegir.add_flag(TrackFlag.CULTURE_2)
ambushed_by_vaegir.add_flag(TrackFlag.SIT_AMBUSHED)
ambushed_by_vaegir.add_flag(TrackFlag.SIT_SIEGE)
ambushed_by_vaegir.add_continue_flag(TrackFlag.CULTURE_1)
ambushed_by_vaegir.add_continue_flag(TrackFlag.CULTURE_3)
ambushed_by_vaegir.add_continue_flag(TrackFlag.CULTURE_4)
ambushed_by_vaegir.add_continue_flag(TrackFlag.CULTURE_5)
ambushed_by_vaegir.add_continue_flag(TrackFlag.CULTURE_6)
ambushed_by_vaegir.add_continue_flag(TrackFlag.SIT_FIGHT)
ambushed_by_vaegir.add_continue_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)

middle_eastern_action = MusicTrack("middle_eastern_action", "middle_eastern_action.ogg")
middle_eastern_action.add_flag(TrackFlag.CULTURE_6)
middle_eastern_action.add_flag(TrackFlag.SIT_AMBUSHED)
middle_eastern_action.add_flag(TrackFlag.SIT_SIEGE)
middle_eastern_action.add_continue_flag(TrackFlag.CULTURE_1)
middle_eastern_action.add_continue_flag(TrackFlag.CULTURE_2)
middle_eastern_action.add_continue_flag(TrackFlag.CULTURE_3)
middle_eastern_action.add_continue_flag(TrackFlag.CULTURE_4)
middle_eastern_action.add_continue_flag(TrackFlag.CULTURE_5)
middle_eastern_action.add_continue_flag(TrackFlag.SIT_FIGHT)
middle_eastern_action.add_continue_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)

arena_1 = MusicTrack("arena_1", "arena_1.ogg")
arena_1.add_flag(TrackFlag.SIT_ARENA)

armorer = MusicTrack("armorer", "armorer.ogg")
armorer.add_flag(TrackFlag.SIT_TRAVEL)

bandit_fight = MusicTrack("bandit_fight", "bandit_fight.ogg")
bandit_fight.add_flag(TrackFlag.SIT_FIGHT)
bandit_fight.add_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)
bandit_fight.add_flag(TrackFlag.SIT_AMBUSHED)

calm_night_2 = MusicTrack("calm_night_2", "calm_night_2.ogg")
calm_night_2.add_flag(TrackFlag.SIT_NIGHT)
calm_night_2.add_continue_flag(TrackFlag.SIT_TAVERN)
calm_night_2.add_continue_flag(TrackFlag.SIT_TOWN)
calm_night_2.add_continue_flag(TrackFlag.SIT_TRAVEL)

capture = MusicTrack("capture", "capture.ogg")
capture.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)

defeated_by_neutral = MusicTrack("defeated_by_neutral", "defeated_by_neutral.ogg")
defeated_by_neutral.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)
defeated_by_neutral.add_flag(TrackFlag.SIT_KILLED)

defeated_by_neutral_2 = MusicTrack("defeated_by_neutral_2", "defeated_by_neutral_2.ogg")
defeated_by_neutral_2.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)
defeated_by_neutral_2.add_flag(TrackFlag.SIT_KILLED)

defeated_by_neutral_3 = MusicTrack("defeated_by_neutral_3", "defeated_by_neutral_3.ogg")
defeated_by_neutral_3.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)
defeated_by_neutral_3.add_flag(TrackFlag.SIT_KILLED)

empty_village = MusicTrack("empty_village", "empty_village.ogg")
empty_village.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)

encounter_hostile_nords = MusicTrack("encounter_hostile_nords", "encounter_hostile_nords.ogg")
encounter_hostile_nords.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)
encounter_hostile_nords.add_flag(TrackFlag.SIT_ENCOUNTER_HOSTILE)

escape = MusicTrack("escape", "escape.ogg")
escape.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)

fight_1 = MusicTrack("fight_1", "fight_1.ogg")
fight_1.add_flag(TrackFlag.SIT_FIGHT)
fight_1.add_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)
fight_1.add_flag(TrackFlag.SIT_AMBUSHED)

fight_2 = MusicTrack("fight_2", "fight_2.ogg")
fight_2.add_flag(TrackFlag.SIT_FIGHT)
fight_2.add_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)
fight_2.add_flag(TrackFlag.SIT_AMBUSHED)

fight_3 = MusicTrack("fight_3", "fight_3.ogg")
fight_3.add_flag(TrackFlag.SIT_FIGHT)
fight_3.add_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)
fight_3.add_flag(TrackFlag.SIT_AMBUSHED)

fight_as_khergit = MusicTrack("fight_as_khergit", "fight_as_khergit.ogg")
fight_as_khergit.add_flag(TrackFlag.CULTURE_3)
fight_as_khergit.add_flag(TrackFlag.SIT_FIGHT)
fight_as_khergit.add_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)
fight_as_khergit.add_flag(TrackFlag.SIT_AMBUSHED)
fight_as_khergit.add_continue_flag(TrackFlag.CULTURE_1)
fight_as_khergit.add_continue_flag(TrackFlag.CULTURE_2)
fight_as_khergit.add_continue_flag(TrackFlag.CULTURE_4)
fight_as_khergit.add_continue_flag(TrackFlag.CULTURE_5)
fight_as_khergit.add_continue_flag(TrackFlag.CULTURE_6)

percussion_battery = MusicTrack("percussion_battery", "percussion_battery.ogg")
percussion_battery.add_flag(TrackFlag.SIT_FIGHT)
percussion_battery.add_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)
percussion_battery.add_flag(TrackFlag.SIT_AMBUSHED)

fight_as_nord = MusicTrack("fight_as_nord", "fight_as_nord.ogg")
fight_as_nord.add_flag(TrackFlag.CULTURE_4)
fight_as_nord.add_flag(TrackFlag.SIT_FIGHT)
fight_as_nord.add_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)
fight_as_nord.add_flag(TrackFlag.SIT_AMBUSHED)
fight_as_nord.add_continue_flag(TrackFlag.CULTURE_1)
fight_as_nord.add_continue_flag(TrackFlag.CULTURE_2)
fight_as_nord.add_continue_flag(TrackFlag.CULTURE_3)
fight_as_nord.add_continue_flag(TrackFlag.CULTURE_5)
fight_as_nord.add_continue_flag(TrackFlag.CULTURE_6)

fight_as_rhodok = MusicTrack("fight_as_rhodok", "fight_as_rhodok.ogg")
fight_as_rhodok.add_flag(TrackFlag.CULTURE_5)
fight_as_rhodok.add_flag(TrackFlag.SIT_FIGHT)
fight_as_rhodok.add_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)
fight_as_rhodok.add_flag(TrackFlag.SIT_AMBUSHED)
fight_as_rhodok.add_continue_flag(TrackFlag.CULTURE_1)
fight_as_rhodok.add_continue_flag(TrackFlag.CULTURE_2)
fight_as_rhodok.add_continue_flag(TrackFlag.CULTURE_3)
fight_as_rhodok.add_continue_flag(TrackFlag.CULTURE_4)
fight_as_rhodok.add_continue_flag(TrackFlag.CULTURE_6)

fight_as_vaegir = MusicTrack("fight_as_vaegir", "fight_as_vaegir.ogg")
fight_as_vaegir.add_flag(TrackFlag.CULTURE_2)
fight_as_vaegir.add_flag(TrackFlag.SIT_FIGHT)
fight_as_vaegir.add_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)
fight_as_vaegir.add_flag(TrackFlag.SIT_AMBUSHED)
fight_as_vaegir.add_continue_flag(TrackFlag.CULTURE_1)
fight_as_vaegir.add_continue_flag(TrackFlag.CULTURE_3)
fight_as_vaegir.add_continue_flag(TrackFlag.CULTURE_4)
fight_as_vaegir.add_continue_flag(TrackFlag.CULTURE_5)
fight_as_vaegir.add_continue_flag(TrackFlag.CULTURE_6)

fight_while_mounted_1 = MusicTrack("fight_while_mounted_1", "fight_while_mounted_1.ogg")
fight_while_mounted_1.add_flag(TrackFlag.SIT_FIGHT)
fight_while_mounted_1.add_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)
fight_while_mounted_1.add_flag(TrackFlag.SIT_AMBUSHED)

fight_while_mounted_2 = MusicTrack("fight_while_mounted_2", "fight_while_mounted_2.ogg")
fight_while_mounted_2.add_flag(TrackFlag.SIT_FIGHT)
fight_while_mounted_2.add_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)
fight_while_mounted_2.add_flag(TrackFlag.SIT_AMBUSHED)

warband_action = MusicTrack("warband_action", "warband_action.ogg")
warband_action.add_flag(TrackFlag.SIT_FIGHT)
warband_action.add_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)
warband_action.add_flag(TrackFlag.SIT_AMBUSHED)

infiltration_khergit = MusicTrack("infiltration_khergit", "infiltration_khergit.ogg")
infiltration_khergit.add_flag(TrackFlag.CULTURE_3)
infiltration_khergit.add_flag(TrackFlag.SIT_TOWN_INFILTRATE)
infiltration_khergit.add_continue_flag(TrackFlag.CULTURE_1)
infiltration_khergit.add_continue_flag(TrackFlag.CULTURE_2)
infiltration_khergit.add_continue_flag(TrackFlag.CULTURE_4)
infiltration_khergit.add_continue_flag(TrackFlag.CULTURE_5)
infiltration_khergit.add_continue_flag(TrackFlag.CULTURE_6)

killed_by_khergit = MusicTrack("killed_by_khergit", "killed_by_khergit.ogg")
killed_by_khergit.add_flag(TrackFlag.CULTURE_3)
killed_by_khergit.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)
killed_by_khergit.add_flag(TrackFlag.SIT_KILLED)

killed_by_swadian = MusicTrack("killed_by_swadian", "killed_by_swadian.ogg")
killed_by_swadian.add_flag(TrackFlag.CULTURE_1)
killed_by_swadian.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)
killed_by_swadian.add_flag(TrackFlag.SIT_KILLED)

lords_hall_khergit = MusicTrack("lords_hall_khergit", "lords_hall_khergit.ogg")
lords_hall_khergit.add_flag(TrackFlag.CULTURE_3)
lords_hall_khergit.add_flag(TrackFlag.SIT_TRAVEL)
lords_hall_khergit.add_continue_flag(TrackFlag.CULTURE_1)
lords_hall_khergit.add_continue_flag(TrackFlag.CULTURE_2)
lords_hall_khergit.add_continue_flag(TrackFlag.CULTURE_4)
lords_hall_khergit.add_continue_flag(TrackFlag.CULTURE_5)
lords_hall_khergit.add_continue_flag(TrackFlag.CULTURE_6)
lords_hall_khergit.add_continue_flag(TrackFlag.SIT_TAVERN)
lords_hall_khergit.add_continue_flag(TrackFlag.SIT_TOWN)
lords_hall_khergit.add_continue_flag(TrackFlag.SIT_NIGHT)

lords_hall_nord = MusicTrack("lords_hall_nord", "lords_hall_nord.ogg")
lords_hall_nord.add_flag(TrackFlag.SIT_TRAVEL)
lords_hall_nord.add_continue_flag(TrackFlag.SIT_TAVERN)
lords_hall_nord.add_continue_flag(TrackFlag.SIT_TOWN)
lords_hall_nord.add_continue_flag(TrackFlag.SIT_NIGHT)

lords_hall_swadian = MusicTrack("lords_hall_swadian", "lords_hall_swadian.ogg")
lords_hall_swadian.add_flag(TrackFlag.SIT_TRAVEL)
lords_hall_swadian.add_continue_flag(TrackFlag.SIT_TAVERN)
lords_hall_swadian.add_continue_flag(TrackFlag.SIT_TOWN)
lords_hall_swadian.add_continue_flag(TrackFlag.SIT_NIGHT)

lords_hall_rhodok = MusicTrack("lords_hall_rhodok", "lords_hall_rhodok.ogg")
lords_hall_rhodok.add_flag(TrackFlag.SIT_TRAVEL)
lords_hall_rhodok.add_continue_flag(TrackFlag.SIT_TAVERN)
lords_hall_rhodok.add_continue_flag(TrackFlag.SIT_TOWN)
lords_hall_rhodok.add_continue_flag(TrackFlag.SIT_NIGHT)

lords_hall_vaegir = MusicTrack("lords_hall_vaegir", "lords_hall_vaegir.ogg")
lords_hall_vaegir.add_flag(TrackFlag.SIT_TRAVEL)
lords_hall_vaegir.add_continue_flag(TrackFlag.SIT_TAVERN)
lords_hall_vaegir.add_continue_flag(TrackFlag.SIT_TOWN)
lords_hall_vaegir.add_continue_flag(TrackFlag.SIT_NIGHT)

mounted_snow_terrain_calm = MusicTrack("mounted_snow_terrain_calm", "mounted_snow_terrain_calm.ogg")
mounted_snow_terrain_calm.add_flag(TrackFlag.SIT_TRAVEL)
mounted_snow_terrain_calm.add_continue_flag(TrackFlag.SIT_TAVERN)
mounted_snow_terrain_calm.add_continue_flag(TrackFlag.SIT_TOWN)
mounted_snow_terrain_calm.add_continue_flag(TrackFlag.SIT_NIGHT)

neutral_infiltration = MusicTrack("neutral_infiltration", "neutral_infiltration.ogg")
neutral_infiltration.add_flag(TrackFlag.SIT_TOWN_INFILTRATE)

outdoor_beautiful_land = MusicTrack("outdoor_beautiful_land", "outdoor_beautiful_land.ogg")
outdoor_beautiful_land.add_flag(TrackFlag.SIT_TRAVEL)
outdoor_beautiful_land.add_continue_flag(TrackFlag.SIT_TAVERN)
outdoor_beautiful_land.add_continue_flag(TrackFlag.SIT_TOWN)
outdoor_beautiful_land.add_continue_flag(TrackFlag.SIT_NIGHT)

retreat = MusicTrack("retreat", "retreat.ogg")
retreat.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)
retreat.add_flag(TrackFlag.SIT_KILLED)

seige_neutral = MusicTrack("seige_neutral", "seige_neutral.ogg")
seige_neutral.add_flag(TrackFlag.SIT_SIEGE)
seige_neutral.add_continue_flag(TrackFlag.SIT_FIGHT)
seige_neutral.add_continue_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)
seige_neutral.add_continue_flag(TrackFlag.SIT_AMBUSHED)

enter_the_juggernaut = MusicTrack("enter_the_juggernaut", "enter_the_juggernaut.ogg")
enter_the_juggernaut.add_flag(TrackFlag.SIT_SIEGE)
enter_the_juggernaut.add_continue_flag(TrackFlag.SIT_FIGHT)
enter_the_juggernaut.add_continue_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)
enter_the_juggernaut.add_continue_flag(TrackFlag.SIT_AMBUSHED)

siege_attempt = MusicTrack("siege_attempt", "siege_attempt.ogg")
siege_attempt.add_flag(TrackFlag.SIT_SIEGE)
siege_attempt.add_continue_flag(TrackFlag.SIT_FIGHT)
siege_attempt.add_continue_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)
siege_attempt.add_continue_flag(TrackFlag.SIT_AMBUSHED)

crazy_battle_music = MusicTrack("crazy_battle_music", "crazy_battle_music.ogg")
crazy_battle_music.add_flag(TrackFlag.SIT_SIEGE)
crazy_battle_music.add_continue_flag(TrackFlag.SIT_FIGHT)
crazy_battle_music.add_continue_flag(TrackFlag.SIT_MULTIPLAYER_FIGHT)
crazy_battle_music.add_continue_flag(TrackFlag.SIT_AMBUSHED)

tavern_1 = MusicTrack("tavern_1", "tavern_1.ogg")
tavern_1.add_flag(TrackFlag.SIT_TAVERN)
tavern_1.add_flag(TrackFlag.SIT_FEAST)

tavern_2 = MusicTrack("tavern_2", "tavern_2.ogg")
tavern_2.add_flag(TrackFlag.SIT_TAVERN)
tavern_2.add_flag(TrackFlag.SIT_FEAST)

town_neutral = MusicTrack("town_neutral", "town_neutral.ogg")
town_neutral.add_flag(TrackFlag.SIT_TOWN)
town_neutral.add_flag(TrackFlag.SIT_TRAVEL)
town_neutral.add_continue_flag(TrackFlag.SIT_TAVERN)
town_neutral.add_continue_flag(TrackFlag.SIT_NIGHT)

town_khergit = MusicTrack("town_khergit", "town_khergit.ogg")
town_khergit.add_flag(TrackFlag.CULTURE_3)
town_khergit.add_flag(TrackFlag.SIT_TOWN)
town_khergit.add_flag(TrackFlag.SIT_TRAVEL)
town_khergit.add_continue_flag(TrackFlag.CULTURE_1)
town_khergit.add_continue_flag(TrackFlag.CULTURE_2)
town_khergit.add_continue_flag(TrackFlag.CULTURE_4)
town_khergit.add_continue_flag(TrackFlag.CULTURE_5)
town_khergit.add_continue_flag(TrackFlag.CULTURE_6)
town_khergit.add_continue_flag(TrackFlag.SIT_TAVERN)
town_khergit.add_continue_flag(TrackFlag.SIT_NIGHT)

town_nord = MusicTrack("town_nord", "town_nord.ogg")
town_nord.add_flag(TrackFlag.CULTURE_4)
town_nord.add_flag(TrackFlag.SIT_TOWN)
town_nord.add_flag(TrackFlag.SIT_TRAVEL)
town_nord.add_continue_flag(TrackFlag.CULTURE_1)
town_nord.add_continue_flag(TrackFlag.CULTURE_2)
town_nord.add_continue_flag(TrackFlag.CULTURE_3)
town_nord.add_continue_flag(TrackFlag.CULTURE_5)
town_nord.add_continue_flag(TrackFlag.CULTURE_6)
town_nord.add_continue_flag(TrackFlag.SIT_TAVERN)
town_nord.add_continue_flag(TrackFlag.SIT_NIGHT)

town_rhodok = MusicTrack("town_rhodok", "town_rhodok.ogg")
town_rhodok.add_flag(TrackFlag.CULTURE_5)
town_rhodok.add_flag(TrackFlag.SIT_TOWN)
town_rhodok.add_flag(TrackFlag.SIT_TRAVEL)
town_rhodok.add_continue_flag(TrackFlag.CULTURE_1)
town_rhodok.add_continue_flag(TrackFlag.CULTURE_2)
town_rhodok.add_continue_flag(TrackFlag.CULTURE_3)
town_rhodok.add_continue_flag(TrackFlag.CULTURE_4)
town_rhodok.add_continue_flag(TrackFlag.CULTURE_6)
town_rhodok.add_continue_flag(TrackFlag.SIT_TAVERN)
town_rhodok.add_continue_flag(TrackFlag.SIT_NIGHT)

town_swadian = MusicTrack("town_swadian", "town_swadian.ogg")
town_swadian.add_flag(TrackFlag.CULTURE_1)
town_swadian.add_flag(TrackFlag.SIT_TOWN)
town_swadian.add_flag(TrackFlag.SIT_TRAVEL)
town_swadian.add_continue_flag(TrackFlag.CULTURE_2)
town_swadian.add_continue_flag(TrackFlag.CULTURE_3)
town_swadian.add_continue_flag(TrackFlag.CULTURE_4)
town_swadian.add_continue_flag(TrackFlag.CULTURE_5)
town_swadian.add_continue_flag(TrackFlag.CULTURE_6)
town_swadian.add_continue_flag(TrackFlag.SIT_TAVERN)
town_swadian.add_continue_flag(TrackFlag.SIT_NIGHT)

town_vaegir = MusicTrack("town_vaegir", "town_vaegir.ogg")
town_vaegir.add_flag(TrackFlag.CULTURE_2)
town_vaegir.add_flag(TrackFlag.SIT_TOWN)
town_vaegir.add_flag(TrackFlag.SIT_TRAVEL)
town_vaegir.add_continue_flag(TrackFlag.CULTURE_1)
town_vaegir.add_continue_flag(TrackFlag.CULTURE_3)
town_vaegir.add_continue_flag(TrackFlag.CULTURE_4)
town_vaegir.add_continue_flag(TrackFlag.CULTURE_5)
town_vaegir.add_continue_flag(TrackFlag.CULTURE_6)
town_vaegir.add_continue_flag(TrackFlag.SIT_TAVERN)
town_vaegir.add_continue_flag(TrackFlag.SIT_NIGHT)

travel_khergit = MusicTrack("travel_khergit", "travel_khergit.ogg")
travel_khergit.add_flag(TrackFlag.CULTURE_3)
travel_khergit.add_flag(TrackFlag.SIT_TRAVEL)
travel_khergit.add_continue_flag(TrackFlag.CULTURE_1)
travel_khergit.add_continue_flag(TrackFlag.CULTURE_2)
travel_khergit.add_continue_flag(TrackFlag.CULTURE_4)
travel_khergit.add_continue_flag(TrackFlag.CULTURE_5)
travel_khergit.add_continue_flag(TrackFlag.CULTURE_6)
travel_khergit.add_continue_flag(TrackFlag.SIT_TAVERN)
travel_khergit.add_continue_flag(TrackFlag.SIT_TOWN)
travel_khergit.add_continue_flag(TrackFlag.SIT_NIGHT)

travel_neutral = MusicTrack("travel_neutral", "travel_neutral.ogg")
travel_neutral.add_flag(TrackFlag.SIT_TRAVEL)
travel_neutral.add_continue_flag(TrackFlag.SIT_TAVERN)
travel_neutral.add_continue_flag(TrackFlag.SIT_TOWN)
travel_neutral.add_continue_flag(TrackFlag.SIT_NIGHT)

travel_nord = MusicTrack("travel_nord", "travel_nord.ogg")
travel_nord.add_flag(TrackFlag.CULTURE_4)
travel_nord.add_flag(TrackFlag.SIT_TRAVEL)
travel_nord.add_continue_flag(TrackFlag.CULTURE_1)
travel_nord.add_continue_flag(TrackFlag.CULTURE_2)
travel_nord.add_continue_flag(TrackFlag.CULTURE_3)
travel_nord.add_continue_flag(TrackFlag.CULTURE_5)
travel_nord.add_continue_flag(TrackFlag.CULTURE_6)
travel_nord.add_continue_flag(TrackFlag.SIT_TAVERN)
travel_nord.add_continue_flag(TrackFlag.SIT_TOWN)
travel_nord.add_continue_flag(TrackFlag.SIT_NIGHT)

travel_rhodok = MusicTrack("travel_rhodok", "travel_rhodok.ogg")
travel_rhodok.add_flag(TrackFlag.CULTURE_5)
travel_rhodok.add_flag(TrackFlag.SIT_TRAVEL)
travel_rhodok.add_continue_flag(TrackFlag.CULTURE_1)
travel_rhodok.add_continue_flag(TrackFlag.CULTURE_2)
travel_rhodok.add_continue_flag(TrackFlag.CULTURE_3)
travel_rhodok.add_continue_flag(TrackFlag.CULTURE_4)
travel_rhodok.add_continue_flag(TrackFlag.CULTURE_6)
travel_rhodok.add_continue_flag(TrackFlag.SIT_TAVERN)
travel_rhodok.add_continue_flag(TrackFlag.SIT_TOWN)
travel_rhodok.add_continue_flag(TrackFlag.SIT_NIGHT)

travel_swadian = MusicTrack("travel_swadian", "travel_swadian.ogg")
travel_swadian.add_flag(TrackFlag.CULTURE_1)
travel_swadian.add_flag(TrackFlag.SIT_TRAVEL)
travel_swadian.add_continue_flag(TrackFlag.CULTURE_2)
travel_swadian.add_continue_flag(TrackFlag.CULTURE_3)
travel_swadian.add_continue_flag(TrackFlag.CULTURE_4)
travel_swadian.add_continue_flag(TrackFlag.CULTURE_5)
travel_swadian.add_continue_flag(TrackFlag.CULTURE_6)
travel_swadian.add_continue_flag(TrackFlag.SIT_TAVERN)
travel_swadian.add_continue_flag(TrackFlag.SIT_TOWN)
travel_swadian.add_continue_flag(TrackFlag.SIT_NIGHT)

travel_vaegir = MusicTrack("travel_vaegir", "travel_vaegir.ogg")
travel_vaegir.add_flag(TrackFlag.CULTURE_2)
travel_vaegir.add_flag(TrackFlag.SIT_TRAVEL)
travel_vaegir.add_continue_flag(TrackFlag.CULTURE_1)
travel_vaegir.add_continue_flag(TrackFlag.CULTURE_3)
travel_vaegir.add_continue_flag(TrackFlag.CULTURE_4)
travel_vaegir.add_continue_flag(TrackFlag.CULTURE_5)
travel_vaegir.add_continue_flag(TrackFlag.CULTURE_6)
travel_vaegir.add_continue_flag(TrackFlag.SIT_TAVERN)
travel_vaegir.add_continue_flag(TrackFlag.SIT_TOWN)
travel_vaegir.add_continue_flag(TrackFlag.SIT_NIGHT)

middle_eastern_travel = MusicTrack("middle_eastern_travel", "middle_eastern_travel.ogg")
middle_eastern_travel.add_flag(TrackFlag.CULTURE_6)
middle_eastern_travel.add_flag(TrackFlag.SIT_TRAVEL)
middle_eastern_travel.add_continue_flag(TrackFlag.CULTURE_1)
middle_eastern_travel.add_continue_flag(TrackFlag.CULTURE_2)
middle_eastern_travel.add_continue_flag(TrackFlag.CULTURE_3)
middle_eastern_travel.add_continue_flag(TrackFlag.CULTURE_4)
middle_eastern_travel.add_continue_flag(TrackFlag.CULTURE_5)
middle_eastern_travel.add_continue_flag(TrackFlag.SIT_TAVERN)
middle_eastern_travel.add_continue_flag(TrackFlag.SIT_TOWN)
middle_eastern_travel.add_continue_flag(TrackFlag.SIT_NIGHT)

uncertain_homestead = MusicTrack("uncertain_homestead", "uncertain_homestead.ogg")
uncertain_homestead.add_flag(TrackFlag.SIT_TRAVEL)
uncertain_homestead.add_continue_flag(TrackFlag.SIT_TAVERN)
uncertain_homestead.add_continue_flag(TrackFlag.SIT_TOWN)
uncertain_homestead.add_continue_flag(TrackFlag.SIT_NIGHT)

hearth_and_brotherhood = MusicTrack("hearth_and_brotherhood", "hearth_and_brotherhood.ogg")
hearth_and_brotherhood.add_flag(TrackFlag.SIT_TRAVEL)
hearth_and_brotherhood.add_continue_flag(TrackFlag.SIT_TAVERN)
hearth_and_brotherhood.add_continue_flag(TrackFlag.SIT_TOWN)
hearth_and_brotherhood.add_continue_flag(TrackFlag.SIT_NIGHT)

tragic_village = MusicTrack("tragic_village", "tragic_village.ogg")
tragic_village.add_flag(TrackFlag.SIT_TRAVEL)
tragic_village.add_continue_flag(TrackFlag.SIT_TAVERN)
tragic_village.add_continue_flag(TrackFlag.SIT_TOWN)
tragic_village.add_continue_flag(TrackFlag.SIT_NIGHT)

victorious_evil = MusicTrack("victorious_evil", "victorious_evil.ogg")
victorious_evil.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)

victorious_neutral_1 = MusicTrack("victorious_neutral_1", "victorious_neutral_1.ogg")
victorious_neutral_1.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)
victorious_neutral_1.add_flag(TrackFlag.SIT_VICTORIOUS)

victorious_neutral_2 = MusicTrack("victorious_neutral_2", "victorious_neutral_2.ogg")
victorious_neutral_2.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)
victorious_neutral_2.add_flag(TrackFlag.SIT_VICTORIOUS)

victorious_neutral_3 = MusicTrack("victorious_neutral_3", "victorious_neutral_3.ogg")
victorious_neutral_3.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)
victorious_neutral_3.add_flag(TrackFlag.SIT_VICTORIOUS)

victorious_swadian = MusicTrack("victorious_swadian", "victorious_swadian.ogg")
victorious_swadian.add_flag(TrackFlag.CULTURE_2)
victorious_swadian.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)
victorious_swadian.add_flag(TrackFlag.SIT_VICTORIOUS)

victorious_vaegir = MusicTrack("victorious_vaegir", "victorious_vaegir.ogg")
victorious_vaegir.add_flag(TrackFlag.CULTURE_2)
victorious_vaegir.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)
victorious_vaegir.add_flag(TrackFlag.SIT_VICTORIOUS)

victorious_vaegir_2 = MusicTrack("victorious_vaegir_2", "victorious_vaegir_2.ogg")
victorious_vaegir_2.add_flag(TrackFlag.CULTURE_2)
victorious_vaegir_2.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)
victorious_vaegir_2.add_flag(TrackFlag.SIT_VICTORIOUS)

wedding = MusicTrack("wedding", "wedding.ogg")
wedding.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)

coronation = MusicTrack("coronation", "coronation.ogg")
coronation.add_flag(TrackFlag.PERSIST_UNTIL_FINISHED)


