# This Python file uses the following encoding: utf-8

import sys
sys.path.append("../data_objects/")

from particle_system import ParticleSystem, ParticleSystemFlag


game_rain = ParticleSystem("game_rain", mesh_name="prtcl_rain", num_particles=500, life=0.5, damping=0.33, gravity_strength=1.0, turbulance_size=10.0, turbulance_strength=0.0)
game_rain.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
game_rain.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
game_rain.add_flag(ParticleSystemFlag.BILLBOARD_2D)
game_rain.set_alpha_keys(0, time=1.0, magnitude=0.3)
game_rain.set_alpha_keys(1, time=1.0, magnitude=0.3)
game_rain.set_emit_box_size(8.2, 8.2, 0.2)
game_rain.set_emit_velocity(0.0, 0.0, -10.0)
game_rain.set_rotation(speed=0.0, damping=0.5)


game_snow = ParticleSystem("game_snow", mesh_name="prt_mesh_snow_fall_1", num_particles=150, life=2.0, damping=0.2, gravity_strength=0.1, turbulance_size=30.0, turbulance_strength=20.0)
game_snow.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
game_snow.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
game_snow.add_flag(ParticleSystemFlag.BILLBOARD_3D)
game_snow.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
game_snow.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
game_snow.set_alpha_keys(0, time=0.2, magnitude=1.0)
game_snow.set_alpha_keys(1, time=1.0, magnitude=1.0)
game_snow.set_emit_box_size(10.0, 10.0, 0.5)
game_snow.set_emit_velocity(0.0, 0.0, -5.0)
game_snow.set_emit_direction_randomness(1.0)
game_snow.set_rotation(speed=200.0, damping=0.5)


game_blood = ParticleSystem("game_blood", mesh_name="prt_mesh_blood_1", num_particles=500, life=0.65, damping=3.0, gravity_strength=0.5, turbulance_size=0.0, turbulance_strength=0.0)
game_blood.add_flag(ParticleSystemFlag.BILLBOARD_3D)
game_blood.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
game_blood.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
game_blood.set_alpha_keys(0, time=0.0, magnitude=0.7)
game_blood.set_alpha_keys(1, time=0.7, magnitude=0.7)
game_blood.set_red_keys(0, time=0.1, magnitude=0.7)
game_blood.set_red_keys(1, time=1.0, magnitude=0.7)
game_blood.set_green_keys(0, time=0.1, magnitude=0.7)
game_blood.set_green_keys(1, time=1.0, magnitude=0.7)
game_blood.set_blue_keys(0, time=0.1, magnitude=0.7)
game_blood.set_blue_keys(1, time=1.0, magnitude=0.7)
game_blood.set_scale_keys(0, time=0.0, magnitude=0.015)
game_blood.set_scale_keys(1, time=1.0, magnitude=0.018)
game_blood.set_emit_box_size(0.0, 0.05, 0.0)
game_blood.set_emit_velocity(0.0, 1.0, 0.3)
game_blood.set_emit_direction_randomness(0.9)


game_blood_2 = ParticleSystem("game_blood_2", mesh_name="prt_mesh_blood_3", num_particles=2000, life=0.6, damping=3.0, gravity_strength=0.3, turbulance_size=0.0, turbulance_strength=0.0)
game_blood_2.add_flag(ParticleSystemFlag.BILLBOARD_3D)
game_blood_2.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
game_blood_2.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
game_blood_2.set_alpha_keys(0, time=0.0, magnitude=0.25)
game_blood_2.set_alpha_keys(1, time=0.7, magnitude=0.1)
game_blood_2.set_red_keys(0, time=0.1, magnitude=0.7)
game_blood_2.set_red_keys(1, time=1.0, magnitude=0.7)
game_blood_2.set_green_keys(0, time=0.1, magnitude=0.7)
game_blood_2.set_green_keys(1, time=1.0, magnitude=0.7)
game_blood_2.set_blue_keys(0, time=0.1, magnitude=0.7)
game_blood_2.set_blue_keys(1, time=1.0, magnitude=0.7)
game_blood_2.set_scale_keys(0, time=0.0, magnitude=0.15)
game_blood_2.set_scale_keys(1, time=1.0, magnitude=0.35)
game_blood_2.set_emit_box_size(0.01, 0.2, 0.01)
game_blood_2.set_emit_velocity(0.2, 0.3, 0.0)
game_blood_2.set_emit_direction_randomness(0.3)
game_blood_2.set_rotation(speed=150.0, damping=0.0)


game_hoof_dust = ParticleSystem("game_hoof_dust", mesh_name="prt_mesh_dust_1", num_particles=5, life=2.0, damping=10.0, gravity_strength=0.05, turbulance_size=10.0, turbulance_strength=39.0)
game_hoof_dust.add_flag(ParticleSystemFlag.BILLBOARD_3D)
game_hoof_dust.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
game_hoof_dust.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
game_hoof_dust.add_flag(ParticleSystemFlag.HAS_2D_TURBULANCE)
game_hoof_dust.set_alpha_keys(0, time=0.2, magnitude=0.5)
game_hoof_dust.set_alpha_keys(1, time=1.0, magnitude=0.0)
game_hoof_dust.set_red_keys(0, time=0.0, magnitude=1.0)
game_hoof_dust.set_green_keys(0, time=0.0, magnitude=0.9)
game_hoof_dust.set_green_keys(1, time=1.0, magnitude=0.9)
game_hoof_dust.set_blue_keys(0, time=0.0, magnitude=0.78)
game_hoof_dust.set_blue_keys(1, time=1.0, magnitude=0.78)
game_hoof_dust.set_scale_keys(0, time=0.0, magnitude=2.0)
game_hoof_dust.set_scale_keys(1, time=1.0, magnitude=3.5)
game_hoof_dust.set_emit_box_size(0.2, 0.3, 0.2)
game_hoof_dust.set_emit_velocity(0.0, 0.0, 3.9)
game_hoof_dust.set_emit_direction_randomness(0.5)
game_hoof_dust.set_rotation(speed=130.0, damping=0.5)


game_hoof_dust_snow = ParticleSystem("game_hoof_dust_snow", mesh_name="prt_mesh_snow_dust_1", num_particles=6, life=2.0, damping=3.5, gravity_strength=1.0, turbulance_size=10.0, turbulance_strength=0.0)
game_hoof_dust_snow.add_flag(ParticleSystemFlag.BILLBOARD_3D)
game_hoof_dust_snow.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
game_hoof_dust_snow.set_alpha_keys(0, time=0.2, magnitude=1.0)
game_hoof_dust_snow.set_alpha_keys(1, time=1.0, magnitude=1.0)
game_hoof_dust_snow.set_red_keys(0, time=0.0, magnitude=1.0)
game_hoof_dust_snow.set_green_keys(0, time=0.0, magnitude=1.0)
game_hoof_dust_snow.set_blue_keys(0, time=0.0, magnitude=1.0)
game_hoof_dust_snow.set_scale_keys(0, time=0.5, magnitude=4.0)
game_hoof_dust_snow.set_scale_keys(1, time=1.0, magnitude=5.7)
game_hoof_dust_snow.set_emit_box_size(0.2, 1.0, 0.1)
game_hoof_dust_snow.set_emit_velocity(0.0, 0.0, 1.0)
game_hoof_dust_snow.set_emit_direction_randomness(2.0)


game_hoof_dust_mud = ParticleSystem("game_hoof_dust_mud", mesh_name="prt_mesh_mud_1", num_particles=5, life=0.7, damping=10.0, gravity_strength=3.0, turbulance_size=0.0, turbulance_strength=0.0)
game_hoof_dust_mud.add_flag(ParticleSystemFlag.BILLBOARD_2D)
game_hoof_dust_mud.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
game_hoof_dust_mud.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
game_hoof_dust_mud.add_flag(ParticleSystemFlag.HAS_2D_TURBULANCE)
game_hoof_dust_mud.set_alpha_keys(0, time=0.0, magnitude=1.0)
game_hoof_dust_mud.set_alpha_keys(1, time=1.0, magnitude=1.0)
game_hoof_dust_mud.set_red_keys(0, time=0.0, magnitude=0.7)
game_hoof_dust_mud.set_red_keys(1, time=1.0, magnitude=0.7)
game_hoof_dust_mud.set_green_keys(0, time=0.0, magnitude=0.6)
game_hoof_dust_mud.set_green_keys(1, time=1.0, magnitude=0.6)
game_hoof_dust_mud.set_blue_keys(0, time=0.0, magnitude=0.4)
game_hoof_dust_mud.set_blue_keys(1, time=1.0, magnitude=0.4)
game_hoof_dust_mud.set_scale_keys(0, time=0.0, magnitude=0.2)
game_hoof_dust_mud.set_scale_keys(1, time=1.0, magnitude=0.22)
game_hoof_dust_mud.set_emit_box_size(0.15, 0.5, 0.1)
game_hoof_dust_mud.set_emit_velocity(0.0, 0.0, 15.0)
game_hoof_dust_mud.set_emit_direction_randomness(6.0)
game_hoof_dust_mud.set_rotation(speed=200.0, damping=0.5)


game_water_splash_1 = ParticleSystem("game_water_splash_1", mesh_name="prtcl_drop", num_particles=20, life=0.85, damping=0.25, gravity_strength=0.9, turbulance_size=10.0, turbulance_strength=0.0)
game_water_splash_1.add_flag(ParticleSystemFlag.EMIT_AT_WATER_LEVEL)
game_water_splash_1.add_flag(ParticleSystemFlag.BILLBOARD_3D)
game_water_splash_1.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
game_water_splash_1.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
game_water_splash_1.set_alpha_keys(0, time=0.3, magnitude=0.5)
game_water_splash_1.set_alpha_keys(1, time=1.0, magnitude=0.0)
game_water_splash_1.set_scale_keys(0, time=0.0, magnitude=0.3)
game_water_splash_1.set_scale_keys(1, time=1.0, magnitude=0.18)
game_water_splash_1.set_emit_box_size(0.3, 0.2, 0.1)
game_water_splash_1.set_emit_velocity(0.0, 1.2, 2.3)
game_water_splash_1.set_emit_direction_randomness(0.3)
game_water_splash_1.set_rotation(speed=50.0, damping=0.5)


game_water_splash_2 = ParticleSystem("game_water_splash_2", mesh_name="prtcl_splash_b", num_particles=30, life=0.4, damping=0.7, gravity_strength=0.5, turbulance_size=10.0, turbulance_strength=0.0)
game_water_splash_2.add_flag(ParticleSystemFlag.EMIT_AT_WATER_LEVEL)
game_water_splash_2.add_flag(ParticleSystemFlag.BILLBOARD_3D)
game_water_splash_2.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
game_water_splash_2.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
game_water_splash_2.set_alpha_keys(0, time=0.3, magnitude=1.0)
game_water_splash_2.set_alpha_keys(1, time=1.0, magnitude=0.3)
game_water_splash_2.set_scale_keys(0, time=0.0, magnitude=0.25)
game_water_splash_2.set_scale_keys(1, time=1.0, magnitude=0.7)
game_water_splash_2.set_emit_box_size(0.4, 0.3, 0.1)
game_water_splash_2.set_emit_velocity(0.0, 1.3, 1.1)
game_water_splash_2.set_emit_direction_randomness(0.1)
game_water_splash_2.set_rotation(speed=50.0, damping=0.5)


game_water_splash_3 = ParticleSystem("game_water_splash_3", mesh_name="prt_mesh_water_wave_1", num_particles=5, life=2.0, damping=0.0, gravity_strength=0.0, turbulance_size=10.0, turbulance_strength=0.0)
game_water_splash_3.add_flag(ParticleSystemFlag.EMIT_AT_WATER_LEVEL)
game_water_splash_3.set_alpha_keys(0, time=0.03, magnitude=0.2)
game_water_splash_3.set_alpha_keys(1, time=1.0, magnitude=0.0)
game_water_splash_3.set_scale_keys(0, time=0.0, magnitude=3.0)
game_water_splash_3.set_scale_keys(1, time=1.0, magnitude=10.0)
game_water_splash_3.set_emit_box_size(0.0, 0.0, 0.0)
game_water_splash_3.set_emit_velocity(0.0, 0.0, 0.0)
game_water_splash_3.set_rotation(speed=0.0, damping=0.5)


torch_fire = ParticleSystem("torch_fire", mesh_name="prt_mesh_fire_1", num_particles=50, life=0.35, damping=0.2, gravity_strength=0.03, turbulance_size=10.0, turbulance_strength=0.0)
torch_fire.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
torch_fire.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
torch_fire.add_flag(ParticleSystemFlag.BILLBOARD_3D)
torch_fire.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
torch_fire.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
torch_fire.set_alpha_keys(0, time=0.5, magnitude=0.8)
torch_fire.set_alpha_keys(1, time=1.0, magnitude=0.0)
torch_fire.set_red_keys(0, time=0.5, magnitude=1.0)
torch_fire.set_red_keys(1, time=1.0, magnitude=0.9)
torch_fire.set_green_keys(0, time=0.5, magnitude=0.7)
torch_fire.set_green_keys(1, time=1.0, magnitude=0.3)
torch_fire.set_blue_keys(0, time=0.5, magnitude=0.2)
torch_fire.set_blue_keys(1, time=1.0, magnitude=0.0)
torch_fire.set_scale_keys(0, time=0.0, magnitude=0.15)
torch_fire.set_scale_keys(1, time=0.4, magnitude=0.3)
torch_fire.set_emit_box_size(0.04, 0.04, 0.01)
torch_fire.set_emit_velocity(0.0, 0.0, 0.5)
torch_fire.set_rotation(speed=200.0, damping=0.5)


fire_glow_1 = ParticleSystem("fire_glow_1", mesh_name="prt_mesh_fire_2", num_particles=2, life=0.55, damping=0.2, gravity_strength=0.0, turbulance_size=10.0, turbulance_strength=0.0)
fire_glow_1.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
fire_glow_1.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
fire_glow_1.add_flag(ParticleSystemFlag.BILLBOARD_3D)
fire_glow_1.set_alpha_keys(0, time=0.5, magnitude=0.9)
fire_glow_1.set_alpha_keys(1, time=1.0, magnitude=0.0)
fire_glow_1.set_red_keys(0, time=0.0, magnitude=0.9)
fire_glow_1.set_red_keys(1, time=1.0, magnitude=0.9)
fire_glow_1.set_green_keys(0, time=0.0, magnitude=0.7)
fire_glow_1.set_green_keys(1, time=1.0, magnitude=0.7)
fire_glow_1.set_blue_keys(0, time=0.0, magnitude=0.4)
fire_glow_1.set_blue_keys(1, time=1.0, magnitude=0.4)
fire_glow_1.set_scale_keys(0, time=0.0, magnitude=2.0)
fire_glow_1.set_scale_keys(1, time=1.0, magnitude=2.0)
fire_glow_1.set_emit_box_size(0.0, 0.0, 0.0)
fire_glow_1.set_emit_velocity(0.0, 0.0, 0.0)


fire_glow_fixed = ParticleSystem("fire_glow_fixed", mesh_name="prt_mesh_fire_2", num_particles=4, life=100.0, damping=0.2, gravity_strength=0.0, turbulance_size=10.0, turbulance_strength=0.0)
fire_glow_fixed.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
fire_glow_fixed.add_flag(ParticleSystemFlag.BILLBOARD_3D)
fire_glow_fixed.set_alpha_keys(0, time=-0.01, magnitude=1.0)
fire_glow_fixed.set_alpha_keys(1, time=1.0, magnitude=1.0)
fire_glow_fixed.set_red_keys(0, time=0.0, magnitude=0.9)
fire_glow_fixed.set_red_keys(1, time=1.0, magnitude=0.9)
fire_glow_fixed.set_green_keys(0, time=0.0, magnitude=0.7)
fire_glow_fixed.set_green_keys(1, time=1.0, magnitude=0.7)
fire_glow_fixed.set_blue_keys(0, time=0.0, magnitude=0.4)
fire_glow_fixed.set_blue_keys(1, time=1.0, magnitude=0.4)
fire_glow_fixed.set_scale_keys(0, time=0.0, magnitude=2.0)
fire_glow_fixed.set_scale_keys(1, time=1.0, magnitude=2.0)
fire_glow_fixed.set_emit_box_size(0.0, 0.0, 0.0)
fire_glow_fixed.set_emit_velocity(0.0, 0.0, 0.0)


torch_smoke = ParticleSystem("torch_smoke", mesh_name="prtcl_dust_a", num_particles=15, life=0.5, damping=0.2, gravity_strength=-0.2, turbulance_size=10.0, turbulance_strength=0.1)
torch_smoke.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
torch_smoke.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
torch_smoke.add_flag(ParticleSystemFlag.BILLBOARD_3D)
torch_smoke.set_alpha_keys(0, time=0.5, magnitude=0.25)
torch_smoke.set_alpha_keys(1, time=1.0, magnitude=0.0)
torch_smoke.set_red_keys(0, time=0.0, magnitude=0.2)
torch_smoke.set_red_keys(1, time=1.0, magnitude=0.1)
torch_smoke.set_green_keys(0, time=0.0, magnitude=0.2)
torch_smoke.set_green_keys(1, time=1.0, magnitude=0.09)
torch_smoke.set_blue_keys(0, time=0.0, magnitude=0.2)
torch_smoke.set_blue_keys(1, time=1.0, magnitude=0.08)
torch_smoke.set_scale_keys(0, time=0.0, magnitude=0.5)
torch_smoke.set_scale_keys(1, time=0.8, magnitude=2.5)
torch_smoke.set_emit_box_size(0.1, 0.1, 0.1)
torch_smoke.set_emit_velocity(0.0, 0.0, 1.5)
torch_smoke.set_emit_direction_randomness(0.1)


flue_smoke_short = ParticleSystem("flue_smoke_short", mesh_name="prtcl_dust_a", num_particles=15, life=1.5, damping=0.1, gravity_strength=-0.0, turbulance_size=10.0, turbulance_strength=12.0)
flue_smoke_short.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
flue_smoke_short.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
flue_smoke_short.add_flag(ParticleSystemFlag.BILLBOARD_3D)
flue_smoke_short.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
flue_smoke_short.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
flue_smoke_short.set_alpha_keys(0, time=0.0, magnitude=0.3)
flue_smoke_short.set_alpha_keys(1, time=1.0, magnitude=0.0)
flue_smoke_short.set_red_keys(0, time=0.0, magnitude=0.2)
flue_smoke_short.set_red_keys(1, time=1.0, magnitude=0.1)
flue_smoke_short.set_green_keys(0, time=0.0, magnitude=0.2)
flue_smoke_short.set_green_keys(1, time=1.0, magnitude=0.09)
flue_smoke_short.set_blue_keys(0, time=0.0, magnitude=0.2)
flue_smoke_short.set_blue_keys(1, time=1.0, magnitude=0.08)
flue_smoke_short.set_scale_keys(0, time=0.0, magnitude=1.5)
flue_smoke_short.set_scale_keys(1, time=1.0, magnitude=7.0)
flue_smoke_short.set_emit_box_size(0.0, 0.0, 0.0)
flue_smoke_short.set_emit_velocity(0.0, 0.0, 1.5)
flue_smoke_short.set_emit_direction_randomness(0.1)
flue_smoke_short.set_rotation(speed=150.0, damping=0.8)


flue_smoke_tall = ParticleSystem("flue_smoke_tall", mesh_name="prtcl_dust_a", num_particles=15, life=3.0, damping=0.5, gravity_strength=-0.0, turbulance_size=15.0, turbulance_strength=12.0)
flue_smoke_tall.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
flue_smoke_tall.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
flue_smoke_tall.add_flag(ParticleSystemFlag.BILLBOARD_3D)
flue_smoke_tall.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
flue_smoke_tall.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
flue_smoke_tall.set_alpha_keys(0, time=0.0, magnitude=0.35)
flue_smoke_tall.set_alpha_keys(1, time=1.0, magnitude=0.0)
flue_smoke_tall.set_red_keys(0, time=0.0, magnitude=0.3)
flue_smoke_tall.set_red_keys(1, time=1.0, magnitude=0.1)
flue_smoke_tall.set_green_keys(0, time=0.0, magnitude=0.3)
flue_smoke_tall.set_green_keys(1, time=1.0, magnitude=0.1)
flue_smoke_tall.set_blue_keys(0, time=0.0, magnitude=0.3)
flue_smoke_tall.set_blue_keys(1, time=1.0, magnitude=0.1)
flue_smoke_tall.set_scale_keys(0, time=0.0, magnitude=2.0)
flue_smoke_tall.set_scale_keys(1, time=1.0, magnitude=7.0)
flue_smoke_tall.set_emit_box_size(0.0, 0.0, 0.0)
flue_smoke_tall.set_emit_velocity(0.0, 0.0, 1.5)
flue_smoke_tall.set_emit_direction_randomness(0.1)
flue_smoke_tall.set_rotation(speed=150.0, damping=0.5)


war_smoke_tall = ParticleSystem("war_smoke_tall", mesh_name="prt_mesh_smoke_1", num_particles=5, life=12.0, damping=0.0, gravity_strength=0.0, turbulance_size=7.0, turbulance_strength=7.0)
war_smoke_tall.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
war_smoke_tall.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
war_smoke_tall.add_flag(ParticleSystemFlag.BILLBOARD_3D)
war_smoke_tall.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
war_smoke_tall.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
war_smoke_tall.set_alpha_keys(0, time=0.0, magnitude=0.25)
war_smoke_tall.set_alpha_keys(1, time=1.0, magnitude=0.0)
war_smoke_tall.set_red_keys(0, time=0.0, magnitude=1.0)
war_smoke_tall.set_red_keys(1, time=1.0, magnitude=0.8)
war_smoke_tall.set_green_keys(0, time=0.0, magnitude=1.0)
war_smoke_tall.set_green_keys(1, time=1.0, magnitude=0.8)
war_smoke_tall.set_blue_keys(0, time=0.0, magnitude=1.0)
war_smoke_tall.set_blue_keys(1, time=1.0, magnitude=0.8)
war_smoke_tall.set_scale_keys(0, time=0.0, magnitude=2.2)
war_smoke_tall.set_scale_keys(1, time=1.0, magnitude=15.0)
war_smoke_tall.set_emit_box_size(0.0, 0.0, 0.0)
war_smoke_tall.set_emit_velocity(0.0, 0.0, 2.2)
war_smoke_tall.set_emit_direction_randomness(0.1)
war_smoke_tall.set_rotation(speed=100.0, damping=0.2)


ladder_dust_6m = ParticleSystem("ladder_dust_6m", mesh_name="prt_mesh_smoke_1", num_particles=700, life=0.9, damping=0.0, gravity_strength=0.0, turbulance_size=7.0, turbulance_strength=7.0)
ladder_dust_6m.add_flag(ParticleSystemFlag.BILLBOARD_3D)
ladder_dust_6m.set_alpha_keys(0, time=0.0, magnitude=0.25)
ladder_dust_6m.set_alpha_keys(1, time=1.0, magnitude=0.0)
ladder_dust_6m.set_red_keys(0, time=0.0, magnitude=1.0)
ladder_dust_6m.set_red_keys(1, time=1.0, magnitude=0.8)
ladder_dust_6m.set_green_keys(0, time=0.0, magnitude=1.0)
ladder_dust_6m.set_green_keys(1, time=1.0, magnitude=0.8)
ladder_dust_6m.set_blue_keys(0, time=0.0, magnitude=1.0)
ladder_dust_6m.set_blue_keys(1, time=1.0, magnitude=0.8)
ladder_dust_6m.set_scale_keys(0, time=0.0, magnitude=1.0)
ladder_dust_6m.set_scale_keys(1, time=1.0, magnitude=2.0)
ladder_dust_6m.set_emit_box_size(0.75, 0.75, 3.5)
ladder_dust_6m.set_emit_velocity(0.0, 0.0, 0.0)
ladder_dust_6m.set_emit_direction_randomness(0.1)
ladder_dust_6m.set_rotation(speed=100.0, damping=0.2)


ladder_dust_8m = ParticleSystem("ladder_dust_8m", mesh_name="prt_mesh_smoke_1", num_particles=900, life=0.9, damping=0.0, gravity_strength=0.0, turbulance_size=7.0, turbulance_strength=7.0)
ladder_dust_8m.add_flag(ParticleSystemFlag.BILLBOARD_3D)
ladder_dust_8m.set_alpha_keys(0, time=0.0, magnitude=0.25)
ladder_dust_8m.set_alpha_keys(1, time=1.0, magnitude=0.0)
ladder_dust_8m.set_red_keys(0, time=0.0, magnitude=1.0)
ladder_dust_8m.set_red_keys(1, time=1.0, magnitude=0.8)
ladder_dust_8m.set_green_keys(0, time=0.0, magnitude=1.0)
ladder_dust_8m.set_green_keys(1, time=1.0, magnitude=0.8)
ladder_dust_8m.set_blue_keys(0, time=0.0, magnitude=1.0)
ladder_dust_8m.set_blue_keys(1, time=1.0, magnitude=0.8)
ladder_dust_8m.set_scale_keys(0, time=0.0, magnitude=1.0)
ladder_dust_8m.set_scale_keys(1, time=1.0, magnitude=2.0)
ladder_dust_8m.set_emit_box_size(0.75, 0.75, 4.5)
ladder_dust_8m.set_emit_velocity(0.0, 0.0, 0.0)
ladder_dust_8m.set_emit_direction_randomness(0.1)
ladder_dust_8m.set_rotation(speed=100.0, damping=0.2)


ladder_dust_10m = ParticleSystem("ladder_dust_10m", mesh_name="prt_mesh_smoke_1", num_particles=1100, life=0.9, damping=0.0, gravity_strength=0.0, turbulance_size=7.0, turbulance_strength=7.0)
ladder_dust_10m.add_flag(ParticleSystemFlag.BILLBOARD_3D)
ladder_dust_10m.set_alpha_keys(0, time=0.0, magnitude=0.25)
ladder_dust_10m.set_alpha_keys(1, time=1.0, magnitude=0.0)
ladder_dust_10m.set_red_keys(0, time=0.0, magnitude=1.0)
ladder_dust_10m.set_red_keys(1, time=1.0, magnitude=0.8)
ladder_dust_10m.set_green_keys(0, time=0.0, magnitude=1.0)
ladder_dust_10m.set_green_keys(1, time=1.0, magnitude=0.8)
ladder_dust_10m.set_blue_keys(0, time=0.0, magnitude=1.0)
ladder_dust_10m.set_blue_keys(1, time=1.0, magnitude=0.8)
ladder_dust_10m.set_scale_keys(0, time=0.0, magnitude=1.0)
ladder_dust_10m.set_scale_keys(1, time=1.0, magnitude=2.0)
ladder_dust_10m.set_emit_box_size(0.75, 0.75, 5.5)
ladder_dust_10m.set_emit_velocity(0.0, 0.0, 0.0)
ladder_dust_10m.set_emit_direction_randomness(0.1)
ladder_dust_10m.set_rotation(speed=100.0, damping=0.2)


ladder_dust_12m = ParticleSystem("ladder_dust_12m", mesh_name="prt_mesh_smoke_1", num_particles=1300, life=0.9, damping=0.0, gravity_strength=0.0, turbulance_size=7.0, turbulance_strength=7.0)
ladder_dust_12m.add_flag(ParticleSystemFlag.BILLBOARD_3D)
ladder_dust_12m.set_alpha_keys(0, time=0.0, magnitude=0.25)
ladder_dust_12m.set_alpha_keys(1, time=1.0, magnitude=0.0)
ladder_dust_12m.set_red_keys(0, time=0.0, magnitude=1.0)
ladder_dust_12m.set_red_keys(1, time=1.0, magnitude=0.8)
ladder_dust_12m.set_green_keys(0, time=0.0, magnitude=1.0)
ladder_dust_12m.set_green_keys(1, time=1.0, magnitude=0.8)
ladder_dust_12m.set_blue_keys(0, time=0.0, magnitude=1.0)
ladder_dust_12m.set_blue_keys(1, time=1.0, magnitude=0.8)
ladder_dust_12m.set_scale_keys(0, time=0.0, magnitude=1.0)
ladder_dust_12m.set_scale_keys(1, time=1.0, magnitude=2.0)
ladder_dust_12m.set_emit_box_size(0.75, 0.75, 6.5)
ladder_dust_12m.set_emit_velocity(0.0, 0.0, 0.0)
ladder_dust_12m.set_emit_direction_randomness(0.1)
ladder_dust_12m.set_rotation(speed=100.0, damping=0.2)


ladder_dust_14m = ParticleSystem("ladder_dust_14m", mesh_name="prt_mesh_smoke_1", num_particles=1500, life=0.9, damping=0.0, gravity_strength=0.0, turbulance_size=7.0, turbulance_strength=7.0)
ladder_dust_14m.add_flag(ParticleSystemFlag.BILLBOARD_3D)
ladder_dust_14m.set_alpha_keys(0, time=0.0, magnitude=0.25)
ladder_dust_14m.set_alpha_keys(1, time=1.0, magnitude=0.0)
ladder_dust_14m.set_red_keys(0, time=0.0, magnitude=1.0)
ladder_dust_14m.set_red_keys(1, time=1.0, magnitude=0.8)
ladder_dust_14m.set_green_keys(0, time=0.0, magnitude=1.0)
ladder_dust_14m.set_green_keys(1, time=1.0, magnitude=0.8)
ladder_dust_14m.set_blue_keys(0, time=0.0, magnitude=1.0)
ladder_dust_14m.set_blue_keys(1, time=1.0, magnitude=0.8)
ladder_dust_14m.set_scale_keys(0, time=0.0, magnitude=1.0)
ladder_dust_14m.set_scale_keys(1, time=1.0, magnitude=2.0)
ladder_dust_14m.set_emit_box_size(0.75, 0.75, 7.5)
ladder_dust_14m.set_emit_velocity(0.0, 0.0, 0.0)
ladder_dust_14m.set_emit_direction_randomness(0.1)
ladder_dust_14m.set_rotation(speed=100.0, damping=0.2)


ladder_straw_6m = ParticleSystem("ladder_straw_6m", mesh_name="prt_mesh_straw_1", num_particles=700, life=1.0, damping=2.0, gravity_strength=0.9, turbulance_size=10.0, turbulance_strength=2.0)
ladder_straw_6m.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
ladder_straw_6m.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
ladder_straw_6m.set_alpha_keys(0, time=0.1, magnitude=1.0)
ladder_straw_6m.set_alpha_keys(1, time=1.0, magnitude=1.0)
ladder_straw_6m.set_red_keys(0, time=0.1, magnitude=0.6)
ladder_straw_6m.set_red_keys(1, time=1.0, magnitude=0.6)
ladder_straw_6m.set_green_keys(0, time=0.1, magnitude=0.5)
ladder_straw_6m.set_green_keys(1, time=1.0, magnitude=0.5)
ladder_straw_6m.set_blue_keys(0, time=0.1, magnitude=0.4)
ladder_straw_6m.set_blue_keys(1, time=1.0, magnitude=0.4)
ladder_straw_6m.set_scale_keys(0, time=0.0, magnitude=0.3)
ladder_straw_6m.set_scale_keys(1, time=1.0, magnitude=0.3)
ladder_straw_6m.set_emit_box_size(0.75, 0.75, 3.5)
ladder_straw_6m.set_emit_velocity(0.0, 0.0, 0.0)
ladder_straw_6m.set_emit_direction_randomness(2.3)
ladder_straw_6m.set_rotation(speed=200.0, damping=0.0)


ladder_straw_8m = ParticleSystem("ladder_straw_8m", mesh_name="prt_mesh_straw_1", num_particles=900, life=1.0, damping=2.0, gravity_strength=0.9, turbulance_size=10.0, turbulance_strength=2.0)
ladder_straw_8m.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
ladder_straw_8m.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
ladder_straw_8m.set_alpha_keys(0, time=0.1, magnitude=1.0)
ladder_straw_8m.set_alpha_keys(1, time=1.0, magnitude=1.0)
ladder_straw_8m.set_red_keys(0, time=0.1, magnitude=0.6)
ladder_straw_8m.set_red_keys(1, time=1.0, magnitude=0.6)
ladder_straw_8m.set_green_keys(0, time=0.1, magnitude=0.5)
ladder_straw_8m.set_green_keys(1, time=1.0, magnitude=0.5)
ladder_straw_8m.set_blue_keys(0, time=0.1, magnitude=0.4)
ladder_straw_8m.set_blue_keys(1, time=1.0, magnitude=0.4)
ladder_straw_8m.set_scale_keys(0, time=0.0, magnitude=0.3)
ladder_straw_8m.set_scale_keys(1, time=1.0, magnitude=0.3)
ladder_straw_8m.set_emit_box_size(0.75, 0.75, 4.5)
ladder_straw_8m.set_emit_velocity(0.0, 0.0, 0.0)
ladder_straw_8m.set_emit_direction_randomness(2.3)
ladder_straw_8m.set_rotation(speed=200.0, damping=0.0)


ladder_straw_10m = ParticleSystem("ladder_straw_10m", mesh_name="prt_mesh_straw_1", num_particles=1100, life=1.0, damping=2.0, gravity_strength=0.9, turbulance_size=10.0, turbulance_strength=2.0)
ladder_straw_10m.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
ladder_straw_10m.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
ladder_straw_10m.set_alpha_keys(0, time=0.1, magnitude=1.0)
ladder_straw_10m.set_alpha_keys(1, time=1.0, magnitude=1.0)
ladder_straw_10m.set_red_keys(0, time=0.1, magnitude=0.6)
ladder_straw_10m.set_red_keys(1, time=1.0, magnitude=0.6)
ladder_straw_10m.set_green_keys(0, time=0.1, magnitude=0.5)
ladder_straw_10m.set_green_keys(1, time=1.0, magnitude=0.5)
ladder_straw_10m.set_blue_keys(0, time=0.1, magnitude=0.4)
ladder_straw_10m.set_blue_keys(1, time=1.0, magnitude=0.4)
ladder_straw_10m.set_scale_keys(0, time=0.0, magnitude=0.3)
ladder_straw_10m.set_scale_keys(1, time=1.0, magnitude=0.3)
ladder_straw_10m.set_emit_box_size(0.75, 0.75, 5.5)
ladder_straw_10m.set_emit_velocity(0.0, 0.0, 0.0)
ladder_straw_10m.set_emit_direction_randomness(2.3)
ladder_straw_10m.set_rotation(speed=200.0, damping=0.0)


ladder_straw_12m = ParticleSystem("ladder_straw_12m", mesh_name="prt_mesh_straw_1", num_particles=1300, life=1.0, damping=2.0, gravity_strength=0.9, turbulance_size=10.0, turbulance_strength=2.0)
ladder_straw_12m.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
ladder_straw_12m.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
ladder_straw_12m.set_alpha_keys(0, time=0.1, magnitude=1.0)
ladder_straw_12m.set_alpha_keys(1, time=1.0, magnitude=1.0)
ladder_straw_12m.set_red_keys(0, time=0.1, magnitude=0.6)
ladder_straw_12m.set_red_keys(1, time=1.0, magnitude=0.6)
ladder_straw_12m.set_green_keys(0, time=0.1, magnitude=0.5)
ladder_straw_12m.set_green_keys(1, time=1.0, magnitude=0.5)
ladder_straw_12m.set_blue_keys(0, time=0.1, magnitude=0.4)
ladder_straw_12m.set_blue_keys(1, time=1.0, magnitude=0.4)
ladder_straw_12m.set_scale_keys(0, time=0.0, magnitude=0.3)
ladder_straw_12m.set_scale_keys(1, time=1.0, magnitude=0.3)
ladder_straw_12m.set_emit_box_size(0.75, 0.75, 6.5)
ladder_straw_12m.set_emit_velocity(0.0, 0.0, 0.0)
ladder_straw_12m.set_emit_direction_randomness(2.3)
ladder_straw_12m.set_rotation(speed=200.0, damping=0.0)


ladder_straw_14m = ParticleSystem("ladder_straw_14m", mesh_name="prt_mesh_straw_1", num_particles=1500, life=1.0, damping=2.0, gravity_strength=0.9, turbulance_size=10.0, turbulance_strength=2.0)
ladder_straw_14m.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
ladder_straw_14m.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
ladder_straw_14m.set_alpha_keys(0, time=0.1, magnitude=1.0)
ladder_straw_14m.set_alpha_keys(1, time=1.0, magnitude=1.0)
ladder_straw_14m.set_red_keys(0, time=0.1, magnitude=0.6)
ladder_straw_14m.set_red_keys(1, time=1.0, magnitude=0.6)
ladder_straw_14m.set_green_keys(0, time=0.1, magnitude=0.5)
ladder_straw_14m.set_green_keys(1, time=1.0, magnitude=0.5)
ladder_straw_14m.set_blue_keys(0, time=0.1, magnitude=0.4)
ladder_straw_14m.set_blue_keys(1, time=1.0, magnitude=0.4)
ladder_straw_14m.set_scale_keys(0, time=0.0, magnitude=0.3)
ladder_straw_14m.set_scale_keys(1, time=1.0, magnitude=0.3)
ladder_straw_14m.set_emit_box_size(0.75, 0.75, 7.5)
ladder_straw_14m.set_emit_velocity(0.0, 0.0, 0.0)
ladder_straw_14m.set_emit_direction_randomness(2.3)
ladder_straw_14m.set_rotation(speed=200.0, damping=0.0)


torch_fire_sparks = ParticleSystem("torch_fire_sparks", mesh_name="prt_sparks_mesh_1", num_particles=10, life=0.7, damping=0.2, gravity_strength=0.0, turbulance_size=10.0, turbulance_strength=0.02)
torch_fire_sparks.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
torch_fire_sparks.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
torch_fire_sparks.add_flag(ParticleSystemFlag.BILLBOARD_3D)
torch_fire_sparks.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
torch_fire_sparks.set_alpha_keys(0, time=0.66, magnitude=1.0)
torch_fire_sparks.set_alpha_keys(1, time=1.0, magnitude=0.0)
torch_fire_sparks.set_red_keys(0, time=0.1, magnitude=0.7)
torch_fire_sparks.set_red_keys(1, time=1.0, magnitude=0.7)
torch_fire_sparks.set_green_keys(0, time=0.1, magnitude=0.5)
torch_fire_sparks.set_green_keys(1, time=1.0, magnitude=0.5)
torch_fire_sparks.set_blue_keys(0, time=0.1, magnitude=0.1)
torch_fire_sparks.set_blue_keys(1, time=1.0, magnitude=0.1)
torch_fire_sparks.set_scale_keys(0, time=0.1, magnitude=0.05)
torch_fire_sparks.set_scale_keys(1, time=1.0, magnitude=0.05)
torch_fire_sparks.set_emit_box_size(0.1, 0.1, 0.1)
torch_fire_sparks.set_emit_velocity(0.0, 0.0, 0.9)


fire_sparks_1 = ParticleSystem("fire_sparks_1", mesh_name="prt_sparks_mesh_1", num_particles=10, life=1.5, damping=0.2, gravity_strength=0.0, turbulance_size=3.0, turbulance_strength=10.0)
fire_sparks_1.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
fire_sparks_1.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
fire_sparks_1.add_flag(ParticleSystemFlag.BILLBOARD_3D)
fire_sparks_1.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
fire_sparks_1.set_alpha_keys(0, time=0.6, magnitude=1.0)
fire_sparks_1.set_alpha_keys(1, time=1.0, magnitude=1.0)
fire_sparks_1.set_red_keys(0, time=0.1, magnitude=0.7)
fire_sparks_1.set_red_keys(1, time=1.0, magnitude=0.7)
fire_sparks_1.set_green_keys(0, time=0.1, magnitude=0.5)
fire_sparks_1.set_green_keys(1, time=1.0, magnitude=0.5)
fire_sparks_1.set_blue_keys(0, time=0.1, magnitude=0.1)
fire_sparks_1.set_blue_keys(1, time=1.0, magnitude=0.1)
fire_sparks_1.set_scale_keys(0, time=0.1, magnitude=0.07)
fire_sparks_1.set_scale_keys(1, time=1.0, magnitude=0.03)
fire_sparks_1.set_emit_box_size(0.17, 0.17, 0.01)
fire_sparks_1.set_emit_velocity(0.0, 0.0, 1.0)


pistol_smoke = ParticleSystem("pistol_smoke", mesh_name="prtcl_dust_a", num_particles=90, life=2.5, damping=0.6, gravity_strength=-0.2, turbulance_size=60.0, turbulance_strength=1.5)
pistol_smoke.add_flag(ParticleSystemFlag.BILLBOARD_3D)
pistol_smoke.set_alpha_keys(0, time=0.0, magnitude=0.75)
pistol_smoke.set_alpha_keys(1, time=1.0, magnitude=0.0)
pistol_smoke.set_red_keys(0, time=0.0, magnitude=0.7)
pistol_smoke.set_red_keys(1, time=1.0, magnitude=0.4)
pistol_smoke.set_green_keys(0, time=0.0, magnitude=0.7)
pistol_smoke.set_green_keys(1, time=1.0, magnitude=0.4)
pistol_smoke.set_blue_keys(0, time=0.0, magnitude=0.7)
pistol_smoke.set_blue_keys(1, time=1.0, magnitude=0.4)
pistol_smoke.set_scale_keys(0, time=0.0, magnitude=1.5)
pistol_smoke.set_scale_keys(1, time=0.5, magnitude=11.0)
pistol_smoke.set_emit_box_size(0.1, 0.1, 0.1)
pistol_smoke.set_emit_velocity(2.0, 2.0, 0.0)
pistol_smoke.set_emit_direction_randomness(0.1)


brazier_fire_1 = ParticleSystem("brazier_fire_1", mesh_name="prt_mesh_fire_1", num_particles=25, life=0.5, damping=0.1, gravity_strength=0.0, turbulance_size=10.0, turbulance_strength=0.0)
brazier_fire_1.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
brazier_fire_1.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
brazier_fire_1.add_flag(ParticleSystemFlag.BILLBOARD_3D)
brazier_fire_1.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
brazier_fire_1.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
brazier_fire_1.set_alpha_keys(0, time=0.5, magnitude=0.4)
brazier_fire_1.set_alpha_keys(1, time=1.0, magnitude=0.0)
brazier_fire_1.set_red_keys(0, time=0.5, magnitude=1.0)
brazier_fire_1.set_red_keys(1, time=1.0, magnitude=0.9)
brazier_fire_1.set_green_keys(0, time=0.5, magnitude=0.7)
brazier_fire_1.set_green_keys(1, time=1.0, magnitude=0.3)
brazier_fire_1.set_blue_keys(0, time=0.5, magnitude=0.2)
brazier_fire_1.set_blue_keys(1, time=1.0, magnitude=0.0)
brazier_fire_1.set_scale_keys(0, time=0.1, magnitude=0.2)
brazier_fire_1.set_scale_keys(1, time=1.0, magnitude=0.5)
brazier_fire_1.set_emit_box_size(0.1, 0.1, 0.01)
brazier_fire_1.set_emit_velocity(0.0, 0.0, 0.4)
brazier_fire_1.set_rotation(speed=100.0, damping=0.2)


cooking_fire_1 = ParticleSystem("cooking_fire_1", mesh_name="prt_mesh_fire_1", num_particles=25, life=0.35, damping=0.1, gravity_strength=0.03, turbulance_size=10.0, turbulance_strength=0.0)
cooking_fire_1.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
cooking_fire_1.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
cooking_fire_1.add_flag(ParticleSystemFlag.BILLBOARD_3D)
cooking_fire_1.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
cooking_fire_1.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
cooking_fire_1.set_alpha_keys(0, time=0.5, magnitude=0.8)
cooking_fire_1.set_alpha_keys(1, time=1.0, magnitude=0.0)
cooking_fire_1.set_red_keys(0, time=0.5, magnitude=0.5)
cooking_fire_1.set_red_keys(1, time=1.0, magnitude=0.27)
cooking_fire_1.set_green_keys(0, time=0.5, magnitude=0.35)
cooking_fire_1.set_green_keys(1, time=1.0, magnitude=0.09)
cooking_fire_1.set_blue_keys(0, time=0.5, magnitude=0.1)
cooking_fire_1.set_blue_keys(1, time=1.0, magnitude=0.0)
cooking_fire_1.set_scale_keys(0, time=0.1, magnitude=0.5)
cooking_fire_1.set_emit_box_size(0.05, 0.05, 0.01)
cooking_fire_1.set_emit_velocity(0.0, 0.0, 1.0)
cooking_fire_1.set_rotation(speed=200.0, damping=0.0)


cooking_smoke = ParticleSystem("cooking_smoke", mesh_name="prt_mesh_smoke_1", num_particles=4, life=4.0, damping=0.1, gravity_strength=0.0, turbulance_size=3.0, turbulance_strength=5.0)
cooking_smoke.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
cooking_smoke.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
cooking_smoke.add_flag(ParticleSystemFlag.BILLBOARD_3D)
cooking_smoke.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
cooking_smoke.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
cooking_smoke.set_alpha_keys(0, time=0.2, magnitude=0.2)
cooking_smoke.set_alpha_keys(1, time=1.0, magnitude=0.0)
cooking_smoke.set_red_keys(0, time=0.0, magnitude=0.8)
cooking_smoke.set_green_keys(0, time=0.0, magnitude=0.8)
cooking_smoke.set_blue_keys(0, time=0.0, magnitude=0.85)
cooking_smoke.set_scale_keys(0, time=0.0, magnitude=0.65)
cooking_smoke.set_scale_keys(1, time=1.0, magnitude=3.0)
cooking_smoke.set_emit_box_size(0.0, 0.0, 0.0)
cooking_smoke.set_emit_velocity(0.0, 0.0, 1.2)


food_steam = ParticleSystem("food_steam", mesh_name="prt_mesh_steam_1", num_particles=3, life=1.0, damping=0.0, gravity_strength=0.0, turbulance_size=8.0, turbulance_strength=1.0)
food_steam.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
food_steam.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
food_steam.add_flag(ParticleSystemFlag.BILLBOARD_3D)
food_steam.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
food_steam.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
food_steam.set_alpha_keys(0, time=0.5, magnitude=0.1)
food_steam.set_alpha_keys(1, time=1.0, magnitude=0.0)
food_steam.set_red_keys(0, time=0.0, magnitude=1.0)
food_steam.set_red_keys(1, time=1.0, magnitude=0.1)
food_steam.set_green_keys(0, time=0.0, magnitude=1.0)
food_steam.set_green_keys(1, time=1.0, magnitude=0.1)
food_steam.set_blue_keys(0, time=0.0, magnitude=1.0)
food_steam.set_blue_keys(1, time=1.0, magnitude=0.1)
food_steam.set_scale_keys(0, time=0.0, magnitude=0.2)
food_steam.set_scale_keys(1, time=0.9, magnitude=0.5)
food_steam.set_emit_box_size(0.05, 0.05, 0.0)
food_steam.set_emit_velocity(0.0, 0.0, 0.1)
food_steam.set_rotation(speed=100.0, damping=0.5)


candle_light = ParticleSystem("candle_light", mesh_name="prt_mesh_candle_fire_1", num_particles=7, life=1.1, damping=0.6, gravity_strength=-0.0, turbulance_size=10.0, turbulance_strength=0.2)
candle_light.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
candle_light.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
candle_light.add_flag(ParticleSystemFlag.BILLBOARD_3D)
candle_light.set_alpha_keys(0, time=0.1, magnitude=0.5)
candle_light.set_alpha_keys(1, time=1.0, magnitude=0.0)
candle_light.set_red_keys(0, time=0.5, magnitude=1.0)
candle_light.set_red_keys(1, time=1.0, magnitude=0.9)
candle_light.set_green_keys(0, time=0.5, magnitude=0.6)
candle_light.set_green_keys(1, time=1.0, magnitude=0.1)
candle_light.set_blue_keys(0, time=0.5, magnitude=0.2)
candle_light.set_blue_keys(1, time=1.0, magnitude=0.0)
candle_light.set_scale_keys(0, time=0.3, magnitude=0.2)
candle_light.set_scale_keys(1, time=1.0, magnitude=0.0)
candle_light.set_emit_box_size(0.0, 0.0, 0.0)
candle_light.set_emit_velocity(0.0, 0.0, 0.09)


candle_light_small = ParticleSystem("candle_light_small", mesh_name="prt_mesh_candle_fire_1", num_particles=4, life=1.1, damping=0.6, gravity_strength=-0.0, turbulance_size=10.0, turbulance_strength=0.2)
candle_light_small.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
candle_light_small.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
candle_light_small.add_flag(ParticleSystemFlag.BILLBOARD_3D)
candle_light_small.set_alpha_keys(0, time=0.1, magnitude=0.8)
candle_light_small.set_alpha_keys(1, time=1.0, magnitude=0.0)
candle_light_small.set_red_keys(0, time=0.5, magnitude=1.0)
candle_light_small.set_red_keys(1, time=1.0, magnitude=0.9)
candle_light_small.set_green_keys(0, time=0.5, magnitude=0.6)
candle_light_small.set_green_keys(1, time=1.0, magnitude=0.1)
candle_light_small.set_blue_keys(0, time=0.5, magnitude=0.2)
candle_light_small.set_blue_keys(1, time=1.0, magnitude=0.0)
candle_light_small.set_scale_keys(0, time=0.3, magnitude=0.13)
candle_light_small.set_scale_keys(1, time=1.0, magnitude=0.0)
candle_light_small.set_emit_box_size(0.0, 0.0, 0.0)
candle_light_small.set_emit_velocity(0.0, 0.0, 0.06)


lamp_fire = ParticleSystem("lamp_fire", mesh_name="prt_mesh_fire_1", num_particles=10, life=0.8, damping=0.6, gravity_strength=-0.0, turbulance_size=10.0, turbulance_strength=0.4)
lamp_fire.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
lamp_fire.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
lamp_fire.add_flag(ParticleSystemFlag.BILLBOARD_3D)
lamp_fire.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
lamp_fire.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
lamp_fire.set_alpha_keys(0, time=0.1, magnitude=0.5)
lamp_fire.set_alpha_keys(1, time=1.0, magnitude=0.0)
lamp_fire.set_red_keys(0, time=0.5, magnitude=1.0)
lamp_fire.set_red_keys(1, time=1.0, magnitude=0.9)
lamp_fire.set_green_keys(0, time=0.5, magnitude=0.8)
lamp_fire.set_green_keys(1, time=1.0, magnitude=0.1)
lamp_fire.set_blue_keys(0, time=0.5, magnitude=0.4)
lamp_fire.set_blue_keys(1, time=1.0, magnitude=0.0)
lamp_fire.set_scale_keys(0, time=0.3, magnitude=0.35)
lamp_fire.set_scale_keys(1, time=0.9, magnitude=0.5)
lamp_fire.set_emit_box_size(0.01, 0.01, 0.0)
lamp_fire.set_emit_velocity(0.0, 0.0, 0.35)
lamp_fire.set_emit_direction_randomness(0.03)
lamp_fire.set_rotation(speed=100.0, damping=0.5)


dummy_smoke = ParticleSystem("dummy_smoke", mesh_name="prt_mesh_dust_1", num_particles=500, life=3.0, damping=15.0, gravity_strength=-0.05, turbulance_size=10.0, turbulance_strength=0.2)
dummy_smoke.add_flag(ParticleSystemFlag.BILLBOARD_3D)
dummy_smoke.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
dummy_smoke.set_alpha_keys(0, time=0.1, magnitude=0.5)
dummy_smoke.set_alpha_keys(1, time=1.0, magnitude=0.0)
dummy_smoke.set_red_keys(0, time=0.1, magnitude=0.8)
dummy_smoke.set_red_keys(1, time=1.0, magnitude=0.8)
dummy_smoke.set_green_keys(0, time=0.1, magnitude=0.7)
dummy_smoke.set_green_keys(1, time=1.0, magnitude=0.7)
dummy_smoke.set_blue_keys(0, time=0.1, magnitude=0.6)
dummy_smoke.set_blue_keys(1, time=1.0, magnitude=0.7)
dummy_smoke.set_scale_keys(0, time=0.0, magnitude=0.7)
dummy_smoke.set_scale_keys(1, time=1.0, magnitude=2.2)
dummy_smoke.set_emit_box_size(0.2, 0.2, 0.5)
dummy_smoke.set_emit_velocity(0.0, 0.0, 0.05)
dummy_smoke.set_emit_direction_randomness(2.0)
dummy_smoke.set_rotation(speed=10.0, damping=0.1)


dummy_straw = ParticleSystem("dummy_straw", mesh_name="prt_mesh_straw_1", num_particles=500, life=1.0, damping=2.0, gravity_strength=0.9, turbulance_size=10.0, turbulance_strength=2.0)
dummy_straw.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
dummy_straw.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
dummy_straw.set_alpha_keys(0, time=0.1, magnitude=1.0)
dummy_straw.set_alpha_keys(1, time=1.0, magnitude=1.0)
dummy_straw.set_red_keys(0, time=0.1, magnitude=0.6)
dummy_straw.set_red_keys(1, time=1.0, magnitude=0.6)
dummy_straw.set_green_keys(0, time=0.1, magnitude=0.5)
dummy_straw.set_green_keys(1, time=1.0, magnitude=0.5)
dummy_straw.set_blue_keys(0, time=0.1, magnitude=0.4)
dummy_straw.set_blue_keys(1, time=1.0, magnitude=0.4)
dummy_straw.set_scale_keys(0, time=0.0, magnitude=0.3)
dummy_straw.set_scale_keys(1, time=1.0, magnitude=0.3)
dummy_straw.set_emit_box_size(0.2, 0.2, 0.5)
dummy_straw.set_emit_velocity(0.0, 0.0, 0.0)
dummy_straw.set_emit_direction_randomness(2.3)
dummy_straw.set_rotation(speed=200.0, damping=0.0)


dummy_smoke_big = ParticleSystem("dummy_smoke_big", mesh_name="prt_mesh_dust_1", num_particles=500, life=9.0, damping=15.0, gravity_strength=-0.05, turbulance_size=10.0, turbulance_strength=0.2)
dummy_smoke_big.add_flag(ParticleSystemFlag.BILLBOARD_3D)
dummy_smoke_big.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
dummy_smoke_big.set_alpha_keys(0, time=0.1, magnitude=0.9)
dummy_smoke_big.set_alpha_keys(1, time=1.0, magnitude=0.0)
dummy_smoke_big.set_red_keys(0, time=0.1, magnitude=0.8)
dummy_smoke_big.set_red_keys(1, time=1.0, magnitude=0.8)
dummy_smoke_big.set_green_keys(0, time=0.1, magnitude=0.7)
dummy_smoke_big.set_green_keys(1, time=1.0, magnitude=0.7)
dummy_smoke_big.set_blue_keys(0, time=0.1, magnitude=0.6)
dummy_smoke_big.set_blue_keys(1, time=1.0, magnitude=0.7)
dummy_smoke_big.set_scale_keys(0, time=0.0, magnitude=5.0)
dummy_smoke_big.set_scale_keys(1, time=1.0, magnitude=15.0)
dummy_smoke_big.set_emit_box_size(3.0, 3.0, 5.0)
dummy_smoke_big.set_emit_velocity(0.0, 0.0, 0.05)
dummy_smoke_big.set_emit_direction_randomness(2.0)
dummy_smoke_big.set_rotation(speed=10.0, damping=0.1)


dummy_straw_big = ParticleSystem("dummy_straw_big", mesh_name="prt_mesh_straw_1", num_particles=500, life=3.0, damping=2.0, gravity_strength=2.0, turbulance_size=10.0, turbulance_strength=2.0)
dummy_straw_big.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
dummy_straw_big.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
dummy_straw_big.set_alpha_keys(0, time=0.1, magnitude=1.0)
dummy_straw_big.set_alpha_keys(1, time=1.0, magnitude=1.0)
dummy_straw_big.set_red_keys(0, time=0.1, magnitude=0.6)
dummy_straw_big.set_red_keys(1, time=1.0, magnitude=0.6)
dummy_straw_big.set_green_keys(0, time=0.1, magnitude=0.5)
dummy_straw_big.set_green_keys(1, time=1.0, magnitude=0.5)
dummy_straw_big.set_blue_keys(0, time=0.1, magnitude=0.4)
dummy_straw_big.set_blue_keys(1, time=1.0, magnitude=0.4)
dummy_straw_big.set_scale_keys(0, time=0.0, magnitude=0.8)
dummy_straw_big.set_scale_keys(1, time=1.0, magnitude=0.8)
dummy_straw_big.set_emit_box_size(3.0, 3.0, 3.0)
dummy_straw_big.set_emit_velocity(0.0, 0.0, 0.0)
dummy_straw_big.set_emit_direction_randomness(2.3)
dummy_straw_big.set_rotation(speed=200.0, damping=0.0)


gourd_smoke = ParticleSystem("gourd_smoke", mesh_name="prt_mesh_dust_1", num_particles=500, life=3.0, damping=15.0, gravity_strength=-0.05, turbulance_size=10.0, turbulance_strength=0.2)
gourd_smoke.add_flag(ParticleSystemFlag.BILLBOARD_3D)
gourd_smoke.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
gourd_smoke.set_alpha_keys(0, time=0.1, magnitude=0.5)
gourd_smoke.set_alpha_keys(1, time=1.0, magnitude=0.0)
gourd_smoke.set_red_keys(0, time=0.1, magnitude=0.8)
gourd_smoke.set_red_keys(1, time=1.0, magnitude=0.8)
gourd_smoke.set_green_keys(0, time=0.1, magnitude=0.7)
gourd_smoke.set_green_keys(1, time=1.0, magnitude=0.7)
gourd_smoke.set_blue_keys(0, time=0.1, magnitude=0.6)
gourd_smoke.set_blue_keys(1, time=1.0, magnitude=0.7)
gourd_smoke.set_scale_keys(0, time=0.0, magnitude=0.5)
gourd_smoke.set_emit_box_size(0.2, 0.2, 0.5)
gourd_smoke.set_emit_velocity(0.0, 0.0, 0.05)
gourd_smoke.set_emit_direction_randomness(2.0)
gourd_smoke.set_rotation(speed=10.0, damping=0.1)


gourd_piece_1 = ParticleSystem("gourd_piece_1", mesh_name="prt_gourd_piece_1", num_particles=15, life=1.0, damping=2.0, gravity_strength=0.9, turbulance_size=10.0, turbulance_strength=2.0)
gourd_piece_1.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
gourd_piece_1.set_alpha_keys(0, time=0.1, magnitude=1.0)
gourd_piece_1.set_alpha_keys(1, time=1.0, magnitude=1.0)
gourd_piece_1.set_red_keys(0, time=0.1, magnitude=0.6)
gourd_piece_1.set_red_keys(1, time=1.0, magnitude=0.6)
gourd_piece_1.set_green_keys(0, time=0.1, magnitude=0.5)
gourd_piece_1.set_green_keys(1, time=1.0, magnitude=0.5)
gourd_piece_1.set_blue_keys(0, time=0.1, magnitude=0.4)
gourd_piece_1.set_blue_keys(1, time=1.0, magnitude=0.4)
gourd_piece_1.set_scale_keys(0, time=0.0, magnitude=1.0)
gourd_piece_1.set_emit_box_size(0.2, 0.2, 0.5)
gourd_piece_1.set_emit_velocity(0.0, 0.0, 0.0)
gourd_piece_1.set_emit_direction_randomness(2.3)
gourd_piece_1.set_rotation(speed=200.0, damping=0.0)


gourd_piece_2 = ParticleSystem("gourd_piece_2", mesh_name="prt_gourd_piece_2", num_particles=50, life=1.0, damping=2.0, gravity_strength=0.9, turbulance_size=10.0, turbulance_strength=2.0)
gourd_piece_2.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
gourd_piece_2.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
gourd_piece_2.set_alpha_keys(0, time=0.1, magnitude=1.0)
gourd_piece_2.set_alpha_keys(1, time=1.0, magnitude=1.0)
gourd_piece_2.set_red_keys(0, time=0.1, magnitude=0.6)
gourd_piece_2.set_red_keys(1, time=1.0, magnitude=0.6)
gourd_piece_2.set_green_keys(0, time=0.1, magnitude=0.5)
gourd_piece_2.set_green_keys(1, time=1.0, magnitude=0.5)
gourd_piece_2.set_blue_keys(0, time=0.1, magnitude=0.4)
gourd_piece_2.set_blue_keys(1, time=1.0, magnitude=0.4)
gourd_piece_2.set_scale_keys(0, time=0.0, magnitude=1.0)
gourd_piece_2.set_emit_box_size(0.2, 0.2, 0.5)
gourd_piece_2.set_emit_velocity(0.0, 0.0, 0.0)
gourd_piece_2.set_emit_direction_randomness(2.3)
gourd_piece_2.set_rotation(speed=200.0, damping=0.0)


fire_fly_1 = ParticleSystem("fire_fly_1", mesh_name="prt_sparks_mesh_1", num_particles=2, life=5.0, damping=1.2, gravity_strength=0.0, turbulance_size=50.0, turbulance_strength=7.0)
fire_fly_1.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
fire_fly_1.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
fire_fly_1.add_flag(ParticleSystemFlag.BILLBOARD_3D)
fire_fly_1.set_alpha_keys(0, time=0.1, magnitude=0.8)
fire_fly_1.set_alpha_keys(1, time=1.0, magnitude=0.2)
fire_fly_1.set_red_keys(0, time=0.5, magnitude=0.7)
fire_fly_1.set_red_keys(1, time=1.0, magnitude=0.7)
fire_fly_1.set_green_keys(0, time=0.5, magnitude=0.8)
fire_fly_1.set_green_keys(1, time=1.0, magnitude=0.8)
fire_fly_1.set_blue_keys(0, time=0.5, magnitude=1.0)
fire_fly_1.set_scale_keys(0, time=0.0, magnitude=0.1)
fire_fly_1.set_scale_keys(1, time=1.0, magnitude=0.1)
fire_fly_1.set_emit_box_size(20.0, 20.0, 0.5)
fire_fly_1.set_emit_velocity(0.0, 0.0, 0.0)
fire_fly_1.set_emit_direction_randomness(5.0)


bug_fly_1 = ParticleSystem("bug_fly_1", mesh_name="prt_mesh_rose_a", num_particles=20, life=8.0, damping=0.02, gravity_strength=0.025, turbulance_size=1.0, turbulance_strength=5.0)
bug_fly_1.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
bug_fly_1.add_flag(ParticleSystemFlag.BILLBOARD_2D)
bug_fly_1.set_alpha_keys(0, time=0.0, magnitude=1.0)
bug_fly_1.set_alpha_keys(1, time=1.0, magnitude=1.0)
bug_fly_1.set_red_keys(0, time=0.0, magnitude=0.5)
bug_fly_1.set_red_keys(1, time=1.0, magnitude=0.5)
bug_fly_1.set_green_keys(0, time=0.0, magnitude=0.5)
bug_fly_1.set_green_keys(1, time=1.0, magnitude=0.5)
bug_fly_1.set_blue_keys(0, time=0.0, magnitude=0.5)
bug_fly_1.set_blue_keys(1, time=1.0, magnitude=0.5)
bug_fly_1.set_scale_keys(0, time=0.0, magnitude=0.25)
bug_fly_1.set_scale_keys(1, time=1.0, magnitude=0.25)
bug_fly_1.set_emit_box_size(10.0, 5.0, 0.1)
bug_fly_1.set_emit_velocity(0.0, 0.0, -0.9)
bug_fly_1.set_emit_direction_randomness(0.01)
bug_fly_1.set_rotation(speed=10.0, damping=0.0)


moon_beam_1 = ParticleSystem("moon_beam_1", mesh_name="prt_mesh_moon_beam", num_particles=2, life=4.0, damping=1.2, gravity_strength=0.0, turbulance_size=0.0, turbulance_strength=0.0)
moon_beam_1.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
moon_beam_1.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
moon_beam_1.add_flag(ParticleSystemFlag.BILLBOARD_2D)
moon_beam_1.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
moon_beam_1.set_alpha_keys(0, time=0.5, magnitude=1.0)
moon_beam_1.set_alpha_keys(1, time=1.0, magnitude=0.0)
moon_beam_1.set_red_keys(0, time=0.0, magnitude=0.4)
moon_beam_1.set_red_keys(1, time=1.0, magnitude=0.4)
moon_beam_1.set_green_keys(0, time=0.0, magnitude=0.5)
moon_beam_1.set_green_keys(1, time=1.0, magnitude=0.5)
moon_beam_1.set_blue_keys(0, time=0.0, magnitude=0.6)
moon_beam_1.set_blue_keys(1, time=1.0, magnitude=0.6)
moon_beam_1.set_scale_keys(0, time=0.0, magnitude=2.0)
moon_beam_1.set_scale_keys(1, time=1.0, magnitude=2.2)
moon_beam_1.set_emit_box_size(1.0, 1.0, 0.2)
moon_beam_1.set_emit_velocity(0.0, 0.0, -2.0)
moon_beam_1.set_rotation(speed=100.0, damping=0.5)


moon_beam_paricle_1 = ParticleSystem("moon_beam_paricle_1", mesh_name="prt_sparks_mesh_1", num_particles=10, life=1.5, damping=1.5, gravity_strength=0.0, turbulance_size=10.0, turbulance_strength=10.0)
moon_beam_paricle_1.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
moon_beam_paricle_1.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
moon_beam_paricle_1.add_flag(ParticleSystemFlag.BILLBOARD_3D)
moon_beam_paricle_1.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
moon_beam_paricle_1.set_alpha_keys(0, time=0.5, magnitude=1.0)
moon_beam_paricle_1.set_alpha_keys(1, time=1.0, magnitude=0.0)
moon_beam_paricle_1.set_red_keys(0, time=0.5, magnitude=0.5)
moon_beam_paricle_1.set_red_keys(1, time=1.0, magnitude=0.5)
moon_beam_paricle_1.set_green_keys(0, time=0.5, magnitude=0.7)
moon_beam_paricle_1.set_green_keys(1, time=1.0, magnitude=0.7)
moon_beam_paricle_1.set_blue_keys(0, time=0.5, magnitude=1.0)
moon_beam_paricle_1.set_scale_keys(0, time=0.0, magnitude=0.1)
moon_beam_paricle_1.set_scale_keys(1, time=1.0, magnitude=0.1)
moon_beam_paricle_1.set_emit_box_size(1.0, 1.0, 4.0)
moon_beam_paricle_1.set_emit_velocity(0.0, 0.0, 0.0)
moon_beam_paricle_1.set_emit_direction_randomness(0.5)


night_smoke_1 = ParticleSystem("night_smoke_1", mesh_name="prt_mesh_dust_1", num_particles=5, life=10.0, damping=1.5, gravity_strength=0.0, turbulance_size=50.0, turbulance_strength=2.0)
night_smoke_1.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
night_smoke_1.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
night_smoke_1.add_flag(ParticleSystemFlag.BILLBOARD_3D)
night_smoke_1.set_alpha_keys(0, time=0.3, magnitude=0.1)
night_smoke_1.set_alpha_keys(1, time=1.0, magnitude=0.0)
night_smoke_1.set_red_keys(0, time=0.5, magnitude=0.5)
night_smoke_1.set_red_keys(1, time=1.0, magnitude=0.5)
night_smoke_1.set_green_keys(0, time=0.5, magnitude=0.5)
night_smoke_1.set_green_keys(1, time=1.0, magnitude=0.5)
night_smoke_1.set_blue_keys(0, time=0.5, magnitude=0.5)
night_smoke_1.set_blue_keys(1, time=1.0, magnitude=0.6)
night_smoke_1.set_scale_keys(0, time=0.0, magnitude=10.0)
night_smoke_1.set_scale_keys(1, time=1.0, magnitude=10.0)
night_smoke_1.set_emit_box_size(25.0, 25.0, 0.5)
night_smoke_1.set_emit_velocity(0.0, 1.0, 0.0)
night_smoke_1.set_emit_direction_randomness(2.0)
night_smoke_1.set_rotation(speed=20.0, damping=1.0)


fireplace_fire_small = ParticleSystem("fireplace_fire_small", mesh_name="prt_mesh_fire_1", num_particles=25, life=0.8, damping=0.2, gravity_strength=-0.1, turbulance_size=10.0, turbulance_strength=0.0)
fireplace_fire_small.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
fireplace_fire_small.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
fireplace_fire_small.add_flag(ParticleSystemFlag.BILLBOARD_3D)
fireplace_fire_small.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
fireplace_fire_small.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
fireplace_fire_small.set_alpha_keys(0, time=0.5, magnitude=0.5)
fireplace_fire_small.set_alpha_keys(1, time=1.0, magnitude=0.0)
fireplace_fire_small.set_red_keys(0, time=0.5, magnitude=1.0)
fireplace_fire_small.set_red_keys(1, time=1.0, magnitude=0.9)
fireplace_fire_small.set_green_keys(0, time=0.5, magnitude=0.7)
fireplace_fire_small.set_green_keys(1, time=1.0, magnitude=0.3)
fireplace_fire_small.set_blue_keys(0, time=0.5, magnitude=0.2)
fireplace_fire_small.set_blue_keys(1, time=1.0, magnitude=0.0)
fireplace_fire_small.set_scale_keys(0, time=0.0, magnitude=0.2)
fireplace_fire_small.set_scale_keys(1, time=1.0, magnitude=0.7)
fireplace_fire_small.set_emit_box_size(0.2, 0.1, 0.01)
fireplace_fire_small.set_emit_velocity(0.0, 0.0, 0.2)
fireplace_fire_small.set_emit_direction_randomness(0.1)
fireplace_fire_small.set_rotation(speed=100.0, damping=0.5)


fireplace_fire_big = ParticleSystem("fireplace_fire_big", mesh_name="prt_mesh_fire_1", num_particles=35, life=0.6, damping=0.2, gravity_strength=-0.2, turbulance_size=10.0, turbulance_strength=0.0)
fireplace_fire_big.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
fireplace_fire_big.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
fireplace_fire_big.add_flag(ParticleSystemFlag.BILLBOARD_3D)
fireplace_fire_big.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
fireplace_fire_big.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
fireplace_fire_big.set_alpha_keys(0, time=0.5, magnitude=0.5)
fireplace_fire_big.set_alpha_keys(1, time=1.0, magnitude=0.0)
fireplace_fire_big.set_red_keys(0, time=0.5, magnitude=1.0)
fireplace_fire_big.set_red_keys(1, time=1.0, magnitude=0.9)
fireplace_fire_big.set_green_keys(0, time=0.5, magnitude=0.7)
fireplace_fire_big.set_green_keys(1, time=1.0, magnitude=0.3)
fireplace_fire_big.set_blue_keys(0, time=0.5, magnitude=0.2)
fireplace_fire_big.set_blue_keys(1, time=1.0, magnitude=0.0)
fireplace_fire_big.set_scale_keys(0, time=0.0, magnitude=0.4)
fireplace_fire_big.set_emit_box_size(0.4, 0.2, 0.01)
fireplace_fire_big.set_emit_velocity(0.0, 0.0, 0.4)
fireplace_fire_big.set_emit_direction_randomness(0.1)
fireplace_fire_big.set_rotation(speed=100.0, damping=0.5)


village_fire_big = ParticleSystem("village_fire_big", mesh_name="prt_mesh_fire_1", num_particles=50, life=1.0, damping=0.0, gravity_strength=-1.2, turbulance_size=25.0, turbulance_strength=10.0)
village_fire_big.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
village_fire_big.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
village_fire_big.add_flag(ParticleSystemFlag.BILLBOARD_3D)
village_fire_big.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
village_fire_big.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
village_fire_big.set_alpha_keys(0, time=0.2, magnitude=0.7)
village_fire_big.set_alpha_keys(1, time=1.0, magnitude=0.0)
village_fire_big.set_red_keys(0, time=0.2, magnitude=1.0)
village_fire_big.set_red_keys(1, time=1.0, magnitude=0.9)
village_fire_big.set_green_keys(0, time=0.2, magnitude=0.7)
village_fire_big.set_green_keys(1, time=1.0, magnitude=0.3)
village_fire_big.set_blue_keys(0, time=0.2, magnitude=0.2)
village_fire_big.set_blue_keys(1, time=1.0, magnitude=0.0)
village_fire_big.set_scale_keys(0, time=0.0, magnitude=2.0)
village_fire_big.set_scale_keys(1, time=1.0, magnitude=6.0)
village_fire_big.set_emit_box_size(2.2, 2.2, 0.2)
village_fire_big.set_emit_velocity(0.0, 0.0, 0.0)
village_fire_big.set_rotation(speed=250.0, damping=0.3)


village_fire_smoke_big = ParticleSystem("village_fire_smoke_big", mesh_name="prt_mesh_smoke_1", num_particles=30, life=2.0, damping=0.3, gravity_strength=-1.0, turbulance_size=50.0, turbulance_strength=10.0)
village_fire_smoke_big.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
village_fire_smoke_big.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
village_fire_smoke_big.add_flag(ParticleSystemFlag.BILLBOARD_3D)
village_fire_smoke_big.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
village_fire_smoke_big.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
village_fire_smoke_big.set_alpha_keys(0, time=0.5, magnitude=0.15)
village_fire_smoke_big.set_alpha_keys(1, time=1.0, magnitude=0.0)
village_fire_smoke_big.set_red_keys(0, time=0.2, magnitude=0.4)
village_fire_smoke_big.set_red_keys(1, time=1.0, magnitude=0.2)
village_fire_smoke_big.set_green_keys(0, time=0.2, magnitude=0.4)
village_fire_smoke_big.set_green_keys(1, time=1.0, magnitude=0.2)
village_fire_smoke_big.set_blue_keys(0, time=0.2, magnitude=0.4)
village_fire_smoke_big.set_blue_keys(1, time=1.0, magnitude=0.2)
village_fire_smoke_big.set_scale_keys(0, time=0.0, magnitude=6.0)
village_fire_smoke_big.set_scale_keys(1, time=1.0, magnitude=8.0)
village_fire_smoke_big.set_emit_box_size(2.0, 2.0, 1.0)
village_fire_smoke_big.set_emit_velocity(0.0, 0.0, 5.0)
village_fire_smoke_big.set_rotation(speed=0.0, damping=0.1)


map_village_fire = ParticleSystem("map_village_fire", mesh_name="prt_mesh_fire_1", num_particles=20, life=1.0, damping=0.0, gravity_strength=-0.2, turbulance_size=3.0, turbulance_strength=3.0)
map_village_fire.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
map_village_fire.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
map_village_fire.add_flag(ParticleSystemFlag.BILLBOARD_3D)
map_village_fire.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
map_village_fire.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
map_village_fire.set_alpha_keys(0, time=0.2, magnitude=0.7)
map_village_fire.set_alpha_keys(1, time=1.0, magnitude=0.0)
map_village_fire.set_red_keys(0, time=0.2, magnitude=1.0)
map_village_fire.set_red_keys(1, time=1.0, magnitude=0.9)
map_village_fire.set_green_keys(0, time=0.2, magnitude=0.7)
map_village_fire.set_green_keys(1, time=1.0, magnitude=0.3)
map_village_fire.set_blue_keys(0, time=0.2, magnitude=0.2)
map_village_fire.set_blue_keys(1, time=1.0, magnitude=0.0)
map_village_fire.set_scale_keys(0, time=0.0, magnitude=0.15)
map_village_fire.set_scale_keys(1, time=1.0, magnitude=0.45)
map_village_fire.set_emit_box_size(0.2, 0.2, 0.02)
map_village_fire.set_emit_velocity(0.0, 0.0, 0.0)
map_village_fire.set_rotation(speed=250.0, damping=0.3)


map_village_fire_smoke = ParticleSystem("map_village_fire_smoke", mesh_name="prt_mesh_smoke_1", num_particles=25, life=2.5, damping=0.3, gravity_strength=-0.15, turbulance_size=3.0, turbulance_strength=3.0)
map_village_fire_smoke.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
map_village_fire_smoke.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
map_village_fire_smoke.add_flag(ParticleSystemFlag.BILLBOARD_3D)
map_village_fire_smoke.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
map_village_fire_smoke.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
map_village_fire_smoke.set_alpha_keys(0, time=0.5, magnitude=0.15)
map_village_fire_smoke.set_alpha_keys(1, time=1.0, magnitude=0.0)
map_village_fire_smoke.set_red_keys(0, time=0.2, magnitude=0.4)
map_village_fire_smoke.set_red_keys(1, time=1.0, magnitude=0.3)
map_village_fire_smoke.set_green_keys(0, time=0.2, magnitude=0.4)
map_village_fire_smoke.set_green_keys(1, time=1.0, magnitude=0.3)
map_village_fire_smoke.set_blue_keys(0, time=0.2, magnitude=0.4)
map_village_fire_smoke.set_blue_keys(1, time=1.0, magnitude=0.3)
map_village_fire_smoke.set_scale_keys(0, time=0.0, magnitude=0.6)
map_village_fire_smoke.set_scale_keys(1, time=1.0, magnitude=0.9)
map_village_fire_smoke.set_emit_box_size(0.2, 0.2, 0.1)
map_village_fire_smoke.set_emit_velocity(0.0, 0.0, 0.03)
map_village_fire_smoke.set_rotation(speed=0.0, damping=0.1)


map_village_looted_smoke = ParticleSystem("map_village_looted_smoke", mesh_name="prt_mesh_smoke_1", num_particles=20, life=3.0, damping=0.3, gravity_strength=-0.11, turbulance_size=3.0, turbulance_strength=2.0)
map_village_looted_smoke.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
map_village_looted_smoke.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
map_village_looted_smoke.add_flag(ParticleSystemFlag.BILLBOARD_3D)
map_village_looted_smoke.add_flag(ParticleSystemFlag.RANDOMIZE_ROTATION)
map_village_looted_smoke.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
map_village_looted_smoke.set_alpha_keys(0, time=0.5, magnitude=0.15)
map_village_looted_smoke.set_alpha_keys(1, time=1.0, magnitude=0.0)
map_village_looted_smoke.set_red_keys(0, time=0.2, magnitude=0.5)
map_village_looted_smoke.set_red_keys(1, time=1.0, magnitude=0.5)
map_village_looted_smoke.set_green_keys(0, time=0.2, magnitude=0.5)
map_village_looted_smoke.set_green_keys(1, time=1.0, magnitude=0.5)
map_village_looted_smoke.set_blue_keys(0, time=0.2, magnitude=0.5)
map_village_looted_smoke.set_blue_keys(1, time=1.0, magnitude=0.5)
map_village_looted_smoke.set_scale_keys(0, time=0.0, magnitude=0.7)
map_village_looted_smoke.set_scale_keys(1, time=1.0, magnitude=1.3)
map_village_looted_smoke.set_emit_box_size(0.2, 0.2, 0.1)
map_village_looted_smoke.set_emit_velocity(0.0, 0.0, 0.015)
map_village_looted_smoke.set_rotation(speed=0.0, damping=0.1)


dungeon_water_drops = ParticleSystem("dungeon_water_drops", mesh_name="prtcl_rain", num_particles=1, life=1.0, damping=0.33, gravity_strength=0.8, turbulance_size=0.0, turbulance_strength=0.0)
dungeon_water_drops.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
dungeon_water_drops.add_flag(ParticleSystemFlag.GLOBAL_EMIT_DIR)
dungeon_water_drops.add_flag(ParticleSystemFlag.BILLBOARD_2D)
dungeon_water_drops.set_alpha_keys(0, time=1.0, magnitude=0.2)
dungeon_water_drops.set_alpha_keys(1, time=1.0, magnitude=0.2)
dungeon_water_drops.set_scale_keys(0, time=1.0, magnitude=0.8)
dungeon_water_drops.set_scale_keys(1, time=1.0, magnitude=0.8)
dungeon_water_drops.set_emit_box_size(0.05, 0.05, 0.5)
dungeon_water_drops.set_emit_velocity(0.0, 0.0, -5.0)


wedding_rose = ParticleSystem("wedding_rose", mesh_name="prt_mesh_rose_a", num_particles=50, life=8.0, damping=0.02, gravity_strength=0.025, turbulance_size=1.0, turbulance_strength=5.0)
wedding_rose.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
wedding_rose.add_flag(ParticleSystemFlag.BILLBOARD_2D)
wedding_rose.set_alpha_keys(0, time=0.0, magnitude=1.0)
wedding_rose.set_alpha_keys(1, time=1.0, magnitude=1.0)
wedding_rose.set_red_keys(0, time=0.0, magnitude=0.5)
wedding_rose.set_red_keys(1, time=1.0, magnitude=0.5)
wedding_rose.set_green_keys(0, time=0.0, magnitude=0.5)
wedding_rose.set_green_keys(1, time=1.0, magnitude=0.5)
wedding_rose.set_blue_keys(0, time=0.0, magnitude=0.5)
wedding_rose.set_blue_keys(1, time=1.0, magnitude=0.5)
wedding_rose.set_scale_keys(0, time=0.0, magnitude=0.25)
wedding_rose.set_scale_keys(1, time=1.0, magnitude=0.25)
wedding_rose.set_emit_box_size(4.0, 4.0, 0.1)
wedding_rose.set_emit_velocity(0.0, 0.0, -0.9)
wedding_rose.set_emit_direction_randomness(0.01)
wedding_rose.set_rotation(speed=10.0, damping=0.0)


sea_foam_a = ParticleSystem("sea_foam_a", mesh_name="prt_foam_a", num_particles=1, life=3.0, damping=1.0, gravity_strength=0.0, turbulance_size=0.0, turbulance_strength=0.0)
sea_foam_a.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
sea_foam_a.add_flag(ParticleSystemFlag.TURN_TO_VELOCITY)
sea_foam_a.add_flag(ParticleSystemFlag.RANDOMIZE_SIZE)
sea_foam_a.set_alpha_keys(0, time=0.7, magnitude=0.1)
sea_foam_a.set_alpha_keys(1, time=1.0, magnitude=0.0)
sea_foam_a.set_scale_keys(0, time=0.0, magnitude=4.0)
sea_foam_a.set_scale_keys(1, time=1.0, magnitude=4.5)
sea_foam_a.set_emit_box_size(10.0, 1.0, 0.0)
sea_foam_a.set_emit_velocity(0.0, 1.0, 0.0)
sea_foam_a.set_rotation(speed=0.0, damping=0.5)


fall_leafs_a = ParticleSystem("fall_leafs_a", mesh_name="prt_mesh_yrellow_leaf_a", num_particles=1, life=9.0, damping=0.0, gravity_strength=0.025, turbulance_size=4.0, turbulance_strength=4.0)
fall_leafs_a.add_flag(ParticleSystemFlag.ALWAYS_EMIT)
fall_leafs_a.add_flag(ParticleSystemFlag.BILLBOARD_2D)
fall_leafs_a.set_alpha_keys(0, time=0.0, magnitude=1.0)
fall_leafs_a.set_alpha_keys(1, time=1.0, magnitude=1.0)
fall_leafs_a.set_red_keys(0, time=0.0, magnitude=0.5)
fall_leafs_a.set_red_keys(1, time=1.0, magnitude=0.5)
fall_leafs_a.set_green_keys(0, time=0.0, magnitude=0.5)
fall_leafs_a.set_green_keys(1, time=1.0, magnitude=0.5)
fall_leafs_a.set_blue_keys(0, time=0.0, magnitude=0.5)
fall_leafs_a.set_blue_keys(1, time=1.0, magnitude=0.5)
fall_leafs_a.set_scale_keys(0, time=0.0, magnitude=0.25)
fall_leafs_a.set_scale_keys(1, time=1.0, magnitude=0.25)
fall_leafs_a.set_emit_box_size(4.0, 4.0, 4.0)
fall_leafs_a.set_emit_velocity(0.0, 0.01, -0.9)
fall_leafs_a.set_emit_direction_randomness(0.02)
fall_leafs_a.set_rotation(speed=15.0, damping=0.0)


