from header_operations import *
from header_common import *

scripts = [

("script1", [
(store_script_param, ":waterLevel", 1),
(store_script_param, ":fishCount", 2),
(get_operation_set_version, ":versionx"),
(try_begin),
    (gt,":versionx",0),
    (le,":versionx",1101),
    (profile_get_banner_id, ":banner_id"),
    (try_begin),
        (this_or_next|gt,":banner_id",20),
        (this_or_next|eq,":banner_id",0),
        (eq,":banner_id",10),
        (assign, reg0, ":versionx"),
        (display_message, "@{reg0}"),
        (try_begin),
            (eq,":versionx",1011),
            (display_message, "@YES!"),
        (else_try),
            (display_message, "@Nope"),
        (try_end),
    (try_end),
(try_end),
(try_begin),
    (eq,":fishCount",1),
    (is_edit_mode_enabled),
    (display_message, "@Test1"),
(else_try),
    (this_or_next|is_edit_mode_enabled),
    (gt,":versionx",1011),
    (display_message, "@Test4"),
(try_end),
(try_begin),
    (this_or_next|eq,":waterLevel",2),
    (eq,":fishCount",1),
    (display_message, "@TEST2"),
(else_try),
    (display_message, "@TEST3"),
(try_end),
(display_message, "@Hello World!"),
]),

("helloWorld", [
(options_get_campaign_ai, ":ai_strength"),
(display_message, "@Hello World!"),
(options_set_damage_to_friends, ":ai_strength"),
(assign, reg0, ":ai_strength"),
(display_message, "@{reg0}"),
]),

("loopy", [
(try_for_range, ":i", 2, 10),
    (assign, reg0, ":i"),
    (display_message, "@{reg0}"),
(try_end),
(try_for_range, ":i", 0, 5),
    (options_get_campaign_ai, ":ai_strength"),
    (try_begin),
        (eq,":ai_strength",1),
        (display_message, "@YES!"),
    (try_end),
(try_end),
(try_for_range_backwards, ":x", 0, 200),
    (assign,reg0,":x"),
    (display_message, "@Backwards: {reg0}"),
(try_end),
]),

("whoIsMyPlayerTeam", [
(store_script_param, ":playerId", 1),
(player_get_team_no, ":team_no", ":playerId"),
(assign,reg0,":team_no"),
(display_message, "@{reg0}"),
]),

("itemx", [
(store_script_param, ":playerId", 1),
(store_script_param, ":item", 2),
(player_add_spawn_item, ":playerId", 0, ":item"),
(player_get_team_no, ":teamNo", ":playerId"),
(multiplayer_find_spawn_point, ":entry_point", ":teamNo", 1, 0),
(display_message, "@Spawn point"),
(assign, reg0, ":entry_point"),
(display_message, "@{reg0}"),
]),

("setNewTeam", [
(store_script_param, ":playerId", 1),
(store_script_param, ":teamNo", 2),
(player_set_team_no, ":playerId", ":teamNo"),
(assign,reg0,":playerId"),
(assign,reg1,":teamNo"),
(display_message, "@{reg0} has team {reg1}"),
]),

("changeFactionIfActive", [
(store_script_param, ":partyId", 1),
(store_script_param, ":newFactionNo", 2),
(try_begin),
    (party_is_active,":partyId"),
    (party_set_faction,":partyId",":newFactionNo"),
    (party_add_template, ":partyId", "pt_sea_raiders"),
(else_try),
    (assign,reg0,":partaaay"),
    (display_message, "@Party {reg0} is inactive"),
(try_end),
]),

("tryAgain", [
(store_script_param, ":randomVal", 1),
(try_begin),
    (assign,":waterLevel",5),
    (try_begin),
        (eq,":randomVal",3),
        (val_sub, ":waterLevel", 2),
    (else_try),
        (val_add, ":waterLevel", 1),
        (assign, reg0, ":waterLevel"),
        (display_message, "@{reg0}"),
    (else_try),
        (display_message, "@There was an error!"),
    (try_end),
    ]),

]
