###################################################
# header_skins.py
# This file contains declarations for skins
# DO NOT EDIT THIS FILE!
###################################################

voice_die        = 0
voice_hit        = 1
voice_grunt      = 2
voice_grunt_long = 3
voice_yell       = 4
voice_warcry     = 5
voice_victory    = 6
voice_stun       = 7

skf_use_morph_key_10 = 0x00000001
skf_use_morph_key_20 = 0x00000002
skf_use_morph_key_30 = 0x00000003
skf_use_morph_key_40 = 0x00000004
skf_use_morph_key_50 = 0x00000005
skf_use_morph_key_60 = 0x00000006
skf_use_morph_key_70 = 0x00000007

chin_size = 0
chin_shape = 1
chin_forward = 2
jaw_width = 3
jaw_position = 4
mouth_nose_distance = 5
mouth_width = 6
cheeks = 7
nose_height = 8
nose_width = 9
nose_size = 10
nose_shape = 11
nose_bridge = 12
cheek_bones = 13
eye_width = 14
eye_to_eye_dist = 15
eye_shape = 16
eye_depth = 17
eyelids = 18
eyebrow_position = 19
eyebrow_height = 20
eyebrow_depth = 21
eyebrow_shape = 22
temple_width = 23
face_depth = 24
face_ratio = 25
face_width = 26

comp_less_than = -1
comp_greater_than = 1
