from header_common import *
from header_animations import *

animations = [

["stand", 0, amf_client_prediction,
  [3.0, "anim_human", 50, 52, arf_use_stand_progress|arf_cyclic, 0, (0,0,0), 0.25],
  [3.0, "anim_human", 60, 62, arf_use_stand_progress|arf_cyclic, 0, (0,0,0), 0.75],
  [3.0, "anim_human", 70, 72, arf_use_stand_progress|arf_cyclic, 0, (0,0,0), 0.25],
  [3.0, "anim_human", 80, 82, arf_use_stand_progress|arf_cyclic|arf_two_handed_blade, 0, (0,0,0), 0.5],
],
["stand_man", 0, amf_client_prediction,
  [11.0, "stand_man", 0, 315, arf_use_stand_progress|arf_cyclic, 0, (0,0,0), 0.25],
],
["stand_player_first_person", 0, amf_client_prediction,
  [3.5, "anim_human", 90, 100, arf_use_stand_progress|arf_cyclic, 0, (0,0,0), 0.25],
  [3.5, "anim_human", 110, 120, arf_use_stand_progress|arf_cyclic, 0, (0,0,0), 0.25],
],
["jump", acf_enforce_lowerbody, amf_priority_jump|amf_play|amf_client_prediction|amf_continue_to_next,
  [1.0, "jump", 22, 46, arf_blend_in_1, ],
],
["jump_loop", acf_enforce_lowerbody, amf_priority_jump|amf_play|amf_client_prediction,
  [0.5, "jump_loop", 0, 14, arf_blend_in_3|arf_cyclic, ],
],
["jump_end", acf_enforce_lowerbody, amf_priority_jump_end|amf_play|amf_client_prediction,
  [0.3, "jump", 48, 55, arf_blend_in_2, ],
],
["jump_end_hard", acf_enforce_lowerbody, amf_priority_jump_end|amf_play|amf_client_prediction,
  [0.6, "jump_end_hard", 36, 54, arf_blend_in_1, ],
],
["stand_unarmed", 0, amf_client_prediction,
  [8, "noweapon_cstance", 0, 100, arf_use_stand_progress|arf_cyclic, 0, (0,0,0), 0.25],
],
["stand_single", 0, amf_client_prediction,
  [9.0, "sword_loop01", 0, 200, arf_use_stand_progress|arf_cyclic, 0, (0,0,0), 0.25],
],
["stand_greatsword", 0, amf_client_prediction,
  [6.0, "greatsword_cstance", 0, 91, arf_use_stand_progress|arf_cyclic, 0, (0,0,0), 0.25],
],
["stand_staff", 0, amf_client_prediction,
  [2.0, "staff_cstance", 0, 60, arf_use_stand_progress|arf_cyclic, ],
],
["stand_crossbow", 0, amf_client_prediction,
  [2.0, "staff_cstance", 0, 60, arf_use_stand_progress|arf_cyclic, ],
],

] # ANIMATIONS END
