from header_common import *
from header_parties import *
from ID_troops import *
from ID_factions import *
from ID_menus import *
from ID_map_icons import *

no_menu = 0
pmf_is_prisoner = 0x0001

party_templates = [

("none", "none", icon_gray_knight|pf_label_small, no_menu, fac_commoners, 7, []),
("rescued_prisoners", "Rescued_Prisoners", icon_gray_knight|pf_label_small, no_menu, fac_commoners, 7, []),
("enemy", "Enemy", icon_gray_knight|pf_label_small, no_menu, fac_undeads, 7, []),
("hero_party", "Hero_Party", icon_gray_knight|pf_label_small, no_menu, fac_commoners, 7, []),
("village_defenders", "Village_Defenders", icon_peasant|pf_label_small, no_menu, fac_commoners, 7, [(trp_farmer,10,20,0),(trp_peasant_woman,0,4,0),]),
("cattle_herd", "Cattle_Herd", icon_cattle|pf_label_small, no_menu, fac_neutral, 7, [(trp_cattle,80,120,0),]),
("looters", "Looters", icon_axeman|pf_label_small, no_menu, fac_outlaws, 312, [(trp_looter,3,45,0),]),
("manhunters", "Manhunters", icon_gray_knight|pf_label_small, no_menu, fac_manhunters, 137, [(trp_manhunter,9,40,0),]),
("steppe_bandits", "Steppe_Bandits", icon_khergit|pf_label_small, no_menu, fac_outlaws, 312, [(trp_steppe_bandit,4,58,0),]),
("taiga_bandits", "Tundra_Bandits", icon_axeman|pf_label_small, no_menu, fac_outlaws, 312, [(trp_taiga_bandit,4,58,0),]),
("desert_bandits", "Desert_Bandits", icon_vaegir_knight|pf_label_small, no_menu, fac_outlaws, 312, [(trp_desert_bandit,4,58,0),]),
("forest_bandits", "Forest_Bandits", icon_axeman|pf_label_small, no_menu, fac_forest_bandits, 312, [(trp_forest_bandit,4,52,0),]),
("mountain_bandits", "Mountain_Bandits", icon_axeman|pf_label_small, no_menu, fac_mountain_bandits, 312, [(trp_mountain_bandit,4,60,0),]),
("sea_raiders", "Sea_Raiders", icon_axeman|pf_label_small, no_menu, fac_outlaws, 312, [(trp_sea_raider,5,50,0),]),
("deserters", "Deserters", icon_vaegir_knight|pf_label_small, no_menu, fac_deserters, 312, []),
("merchant_caravan", "Merchant_Caravan", icon_gray_knight|pf_label_small|pf_auto_remove_in_town|pf_quest_party, no_menu, fac_commoners, 11, [(trp_caravan_master,1,1,0),(trp_caravan_guard,5,25,0),]),
("troublesome_bandits", "Troublesome_Bandits", icon_axeman|pf_label_small|pf_quest_party, no_menu, fac_outlaws, 312, [(trp_bandit,14,55,0),]),
("bandits_awaiting_ransom", "Bandits_Awaiting_Ransom", icon_axeman|pf_label_small|pf_auto_remove_in_town|pf_quest_party, no_menu, fac_neutral, 312, [(trp_bandit,24,58,0),(trp_kidnapped_girl,1,1,pmf_is_prisoner),]),
("kidnapped_girl", "Kidnapped_Girl", icon_woman|pf_label_small|pf_quest_party, no_menu, fac_neutral, 7, [(trp_kidnapped_girl,1,1,0),]),
("village_farmers", "Village_Farmers", icon_peasant|pf_label_small|pf_civilian, no_menu, fac_innocents, 7, [(trp_farmer,5,10,0),(trp_peasant_woman,3,8,0),]),
("spy_partners", "Unremarkable_Travellers", icon_gray_knight|pf_label_small|pf_default_behavior|pf_quest_party, no_menu, fac_neutral, 7, [(trp_spy_partner,1,1,0),(trp_caravan_guard,5,11,0),]),
("runaway_serfs", "Runaway_Serfs", icon_peasant|pf_label_small|pf_default_behavior|pf_quest_party, no_menu, fac_neutral, 7, [(trp_farmer,6,7,0),(trp_peasant_woman,3,3,0),]),
("spy", "Ordinary_Townsman", icon_gray_knight|pf_label_small|pf_default_behavior|pf_quest_party, no_menu, fac_neutral, 7, [(trp_spy,1,1,0),]),
("sacrificed_messenger", "Sacrificed_Messenger", icon_gray_knight|pf_label_small|pf_default_behavior|pf_quest_party, no_menu, fac_neutral, 7, []),
("forager_party", "Foraging_Party", icon_gray_knight|pf_label_small|pf_show_faction, no_menu, fac_commoners, 7, []),
("scout_party", "Scouts", icon_gray_knight|pf_label_small|pf_show_faction, no_menu, fac_commoners, 312, []),
("patrol_party", "Patrol", icon_gray_knight|pf_label_small|pf_show_faction, no_menu, fac_commoners, 137, []),
("messenger_party", "Messenger", icon_gray_knight|pf_label_small|pf_show_faction, no_menu, fac_commoners, 7, []),
("raider_party", "Raiders", icon_gray_knight|pf_label_small|pf_quest_party, no_menu, fac_commoners, 312, []),
("raider_captives", "Raider_Captives", pf_label_small, no_menu, fac_commoners, 0, [(trp_peasant_woman,6,30,pmf_is_prisoner),]),
("kingdom_caravan_party", "Caravan", icon_mule|pf_label_small|pf_show_faction, no_menu, fac_commoners, 7, [(trp_caravan_master,1,1,0),(trp_caravan_guard,12,40,0),]),
("prisoner_train_party", "Prisoner_Train", icon_gray_knight|pf_label_small|pf_show_faction, no_menu, fac_commoners, 7, []),
("default_prisoners", "Default_Prisoners", pf_label_small, no_menu, fac_commoners, 0, [(trp_bandit,5,10,pmf_is_prisoner),]),
("routed_warriors", "Routed_Enemies", icon_vaegir_knight|pf_label_small, no_menu, fac_commoners, 137, []),
("center_reinforcements", "Reinforcements", icon_axeman|pf_label_small, no_menu, fac_commoners, 137, [(trp_townsman,5,30,0),(trp_watchman,4,20,0),]),
("kingdom_hero_party", "War_Party", icon_flagbearer_a|pf_label_small|pf_default_behavior|pf_show_faction, no_menu, fac_commoners, 137, []),
("kingdom_1_reinforcements_a", "{!}kingdom_1_reinforcements_a", pf_label_small, no_menu, fac_commoners, 0, [(trp_swadian_recruit,5,10,0),(trp_swadian_militia,2,4,0),]),
("kingdom_1_reinforcements_b", "{!}kingdom_1_reinforcements_b", pf_label_small, no_menu, fac_commoners, 0, [(trp_swadian_footman,3,6,0),(trp_swadian_skirmisher,2,4,0),]),
("kingdom_1_reinforcements_c", "{!}kingdom_1_reinforcements_c", pf_label_small, no_menu, fac_commoners, 0, [(trp_swadian_man_at_arms,2,4,0),(trp_swadian_crossbowman,1,2,0),]),
("kingdom_2_reinforcements_a", "{!}kingdom_2_reinforcements_a", pf_label_small, no_menu, fac_commoners, 0, [(trp_vaegir_recruit,5,10,0),(trp_vaegir_footman,2,4,0),]),
("kingdom_2_reinforcements_b", "{!}kingdom_2_reinforcements_b", pf_label_small, no_menu, fac_commoners, 0, [(trp_vaegir_veteran,2,4,0),(trp_vaegir_skirmisher,2,4,0),(trp_vaegir_footman,1,2,0),]),
("kingdom_2_reinforcements_c", "{!}kingdom_2_reinforcements_c", pf_label_small, no_menu, fac_commoners, 0, [(trp_vaegir_horseman,2,3,0),(trp_vaegir_infantry,1,2,0),]),
("kingdom_3_reinforcements_a", "{!}kingdom_3_reinforcements_a", pf_label_small, no_menu, fac_commoners, 0, [(trp_khergit_tribesman,3,5,0),(trp_khergit_skirmisher,4,9,0),]),
("kingdom_3_reinforcements_b", "{!}kingdom_3_reinforcements_b", pf_label_small, no_menu, fac_commoners, 0, [(trp_khergit_horseman,2,4,0),(trp_khergit_horse_archer,2,4,0),(trp_khergit_skirmisher,1,2,0),]),
("kingdom_3_reinforcements_c", "{!}kingdom_3_reinforcements_c", pf_label_small, no_menu, fac_commoners, 0, [(trp_khergit_horseman,2,4,0),(trp_khergit_veteran_horse_archer,2,3,0),]),
("kingdom_4_reinforcements_a", "{!}kingdom_4_reinforcements_a", pf_label_small, no_menu, fac_commoners, 0, [(trp_nord_footman,5,10,0),(trp_nord_recruit,2,4,0),]),
("kingdom_4_reinforcements_b", "{!}kingdom_4_reinforcements_b", pf_label_small, no_menu, fac_commoners, 0, [(trp_nord_huntsman,2,5,0),(trp_nord_archer,2,3,0),(trp_nord_footman,1,2,0),]),
("kingdom_4_reinforcements_c", "{!}kingdom_4_reinforcements_c", pf_label_small, no_menu, fac_commoners, 0, [(trp_nord_warrior,3,5,0),]),
("kingdom_5_reinforcements_a", "{!}kingdom_5_reinforcements_a", pf_label_small, no_menu, fac_commoners, 0, [(trp_rhodok_tribesman,5,10,0),(trp_rhodok_spearman,2,4,0),]),
("kingdom_5_reinforcements_b", "{!}kingdom_5_reinforcements_b", pf_label_small, no_menu, fac_commoners, 0, [(trp_rhodok_crossbowman,3,6,0),(trp_rhodok_trained_crossbowman,2,4,0),]),
("kingdom_5_reinforcements_c", "{!}kingdom_5_reinforcements_c", pf_label_small, no_menu, fac_commoners, 0, [(trp_rhodok_veteran_spearman,2,3,0),(trp_rhodok_veteran_crossbowman,1,2,0),]),
("kingdom_6_reinforcements_a", "{!}kingdom_6_reinforcements_a", pf_label_small, no_menu, fac_commoners, 0, [(trp_sarranid_recruit,5,10,0),(trp_sarranid_footman,2,4,0),]),
("kingdom_6_reinforcements_b", "{!}kingdom_6_reinforcements_b", pf_label_small, no_menu, fac_commoners, 0, [(trp_sarranid_skirmisher,2,4,0),(trp_sarranid_veteran_footman,2,3,0),(trp_sarranid_footman,1,3,0),]),
("kingdom_6_reinforcements_c", "{!}kingdom_6_reinforcements_c", pf_label_small, no_menu, fac_commoners, 0, [(trp_sarranid_horseman,3,5,0),]),
("steppe_bandit_lair", "Steppe_Bandit_Lair", icon_bandit_lair|pf_is_static|pf_label_small|pf_hide_defenders, no_menu, fac_neutral, 312, [(trp_steppe_bandit,15,58,0),]),
("taiga_bandit_lair", "Tundra_Bandit_Lair", icon_bandit_lair|pf_is_static|pf_label_small|pf_hide_defenders, no_menu, fac_neutral, 312, [(trp_taiga_bandit,15,58,0),]),
("desert_bandit_lair", "Desert_Bandit_Lair", icon_bandit_lair|pf_is_static|pf_label_small|pf_hide_defenders, no_menu, fac_neutral, 312, [(trp_desert_bandit,15,58,0),]),
("forest_bandit_lair", "Forest_Bandit_Camp", icon_bandit_lair|pf_is_static|pf_label_small|pf_hide_defenders, no_menu, fac_neutral, 312, [(trp_forest_bandit,15,58,0),]),
("mountain_bandit_lair", "Mountain_Bandit_Hideout", icon_bandit_lair|pf_is_static|pf_label_small|pf_hide_defenders, no_menu, fac_neutral, 312, [(trp_mountain_bandit,15,58,0),]),
("sea_raider_lair", "Sea_Raider_Landing", icon_bandit_lair|pf_is_static|pf_label_small|pf_hide_defenders, no_menu, fac_neutral, 312, [(trp_sea_raider,15,50,0),]),
("looter_lair", "Kidnappers'_Hideout", icon_bandit_lair|pf_is_static|pf_label_small|pf_hide_defenders, no_menu, fac_neutral, 312, [(trp_looter,15,25,0),]),
("bandit_lair_templates_end", "{!}bandit_lair_templates_end", icon_axeman|pf_is_static|pf_label_small, no_menu, fac_outlaws, 312, [(trp_sea_raider,15,50,0),]),
("leaded_looters", "Band_of_robbers", icon_axeman|pf_label_small|pf_quest_party, no_menu, fac_neutral, 312, [(trp_looter_leader,1,1,0),(trp_looter,3,3,0),]),

] # PARTY TEMPLATES END
