from header_common import *
from header_parties import *
from ID_troops import *
from ID_factions import *
from ID_menus import *
from ID_party_templates import *
from ID_map_icons import *

no_menu = 0
pt_none = 0
pf_town = pf_is_static|pf_always_visible|pf_show_faction|pf_label_large
pf_castle = pf_is_static|pf_always_visible|pf_show_faction|pf_label_medium
pf_village = pf_is_static|pf_always_visible|pf_hide_defenders|pf_label_small

parties = [

("main_party", "Main Party", pf_label_small|pf_limit_members, no_menu, pt_none, fac_player_faction, 0, ai_bhvr_hold, 0, (17.0,52.5), [(trp_player,1,0),]),
("temp_party", "{!}temp party", pf_disabled|pf_label_small, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (0.0,0.0), []),
("camp_bandits", "{!}camp bandits", pf_disabled|pf_label_small, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (1.0,1.0), [(trp_temp_troop,3,0),]),
("temp_party_2", "{!}temp party 2", pf_disabled|pf_label_small, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (0.0,0.0), []),
("temp_casualties", "{!}casualties", pf_disabled|pf_label_small, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1.0,1.0), []),
("temp_casualties_2", "{!}casualties", pf_disabled|pf_label_small, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1.0,1.0), []),
("temp_casualties_3", "{!}casualties", pf_disabled|pf_label_small, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1.0,1.0), []),
("temp_wounded", "{!}enemies wounded", pf_disabled|pf_label_small, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1.0,1.0), []),
("temp_killed", "{!}enemies killed", pf_disabled|pf_label_small, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1.0,1.0), []),
("main_party_backup", "{!} ", pf_disabled|pf_label_small, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1.0,1.0), []),
("encountered_party_backup", "{!} ", pf_disabled|pf_label_small, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1.0,1.0), []),
("collective_friends_backup", "{!} ", pf_disabled|pf_label_small, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1.0,1.0), []),
("player_casualties", "{!} ", pf_disabled|pf_label_small, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1.0,1.0), []),
("enemy_casualties", "{!} ", pf_disabled|pf_label_small, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1.0,1.0), []),
("ally_casualties", "{!} ", pf_disabled|pf_label_small, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1.0,1.0), []),
("collective_enemy", "{!}collective enemy", pf_disabled|pf_label_small, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1.0,1.0), []),
("collective_ally", "{!}collective ally", pf_disabled|pf_label_small, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1.0,1.0), []),
("collective_friends", "{!}collective ally", pf_disabled|pf_label_small, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1.0,1.0), []),
("total_enemy_casualties", "{!} ", pf_disabled|pf_label_small, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1.0,1.0), []),
("routed_enemies", "{!}routed enemies", pf_disabled|pf_label_small, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1.0,1.0), []),
("zendar", "Zendar", icon_town|pf_disabled|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (18.0,60.0), []),
("town_1", "Sargoth", icon_town|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-17.6,79.7), [], 170.0),
("town_2", "Tihr", icon_town|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-53.5,78.4), [], 120.0),
("town_3", "Veluca", icon_town|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-57.4,-44.5), [], 80.0),
("town_4", "Suno", icon_town|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-70.0,15.4), [], 290.0),
("town_5", "Jelkala", icon_town|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-74.6,-79.7), [], 90.0),
("town_6", "Praven", icon_town|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-96.0,26.4), [], 155.0),
("town_7", "Uxkhal", icon_town|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-50.0,-8.5), [], 240.0),
("town_8", "Reyvadin", icon_town|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (48.44,39.3), [], 175.0),
("town_9", "Khudan", icon_town_snow|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (94.0,65.2), [], 90.0),
("town_10", "Tulga", icon_town_steppe|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (135.5,-22.0), [], 310.0),
("town_11", "Curaw", icon_town_snow|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (43.0,67.5), [], 150.0),
("town_12", "Wercheg", icon_town|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-1.2,108.9), [], 25.0),
("town_13", "Rivacheg", icon_town|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (64.8,113.7), [], 60.0),
("town_14", "Halmar", icon_town_steppe|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (55.5,-45.0), [], 135.0),
("town_15", "Yalen", icon_town|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-132.8,-47.3), [], 45.0),
("town_16", "Dhirim", icon_town|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (14.0,-2.0), []),
("town_17", "Ichamur", icon_town_steppe|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (121.8,8.6), [], 90.0),
("town_18", "Narra", icon_town_steppe|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (88.0,-26.5), [], 135.0),
("town_19", "Shariz", icon_town_desert|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (15.0,-107.0), [], 45.0),
("town_20", "Durquba", icon_town_desert|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (90.0,-95.1), [], 270.0),
("town_21", "Ahmerrad", icon_town_desert|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (130.5,-78.5), [], 330.0),
("town_22", "Bariyye", icon_town_desert|pf_is_static|pf_label_small|pf_label_large|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (165.0,-106.7), [], 225.0),
("castle_1", "Culmarr Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-101.3,-21.0), [], 50.0),
("castle_2", "Malayurg Castle", icon_castle_b|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (97.5,-2.2), [], 75.0),
("castle_3", "Bulugha Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (47.5,111.3), [], 100.0),
("castle_4", "Radoghir Castle", icon_castle_c|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (32.5,47.8), [], 180.0),
("castle_5", "Tehlrog Castle", icon_castle_c|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-4.8,63.7), [], 90.0),
("castle_6", "Tilbaut Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (37.6,17.1), [], 55.0),
("castle_7", "Sungetche Castle", icon_castle_snow_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (109.5,41.5), [], 45.0),
("castle_8", "Jeirbe Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (35.2,89.0), [], 30.0),
("castle_9", "Jamiche Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-7.5,-82.6), [], 100.0),
("castle_10", "Alburq Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (24.2,96.85), [], 110.0),
("castle_11", "Curin Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-27.5,83.46), [], 75.0),
("castle_12", "Chalbek Castle", icon_castle_b|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-84.75,105.5), [], 95.0),
("castle_13", "Kelredan Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-10.6,17.6), [], 115.0),
("castle_14", "Maras Castle", icon_castle_c|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-122.4,-18.1), [], 90.0),
("castle_15", "Ergellon Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-52.5,-28.0), [], 235.0),
("castle_16", "Almerra Castle", icon_castle_c|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-10.6,-65.6), [], 45.0),
("castle_17", "Distar Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (140.3,-10.8), [], 15.0),
("castle_18", "Ismirala Castle", icon_castle_snow_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (14.4,70.1), [], 300.0),
("castle_19", "Yruma Castle", icon_castle_snow_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (69.5,55.6), [], 280.0),
("castle_20", "Derchios Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (16.0,11.5), [], 260.0),
("castle_21", "Ibdeles Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-73.0,-89.5), [], 260.0),
("castle_22", "Unuzdaq Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (33.0,-64.0), [], 260.0),
("castle_23", "Tevarin Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-124.8,44.3), [], 80.0),
("castle_24", "Reindi Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (24.9,-35.6), [], 260.0),
("castle_25", "Ryibelet Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-57.0,30.6), [], 260.0),
("castle_26", "Senuzgda Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-2.5,-9.5), [], 260.0),
("castle_27", "Rindyar Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (63.3,-2.0), [], 260.0),
("castle_28", "Grunwalder Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-36.4,-39.3), [], 260.0),
("castle_29", "Nelag Castle", icon_castle_snow_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (147.7,50.4), [], 280.0),
("castle_30", "Asugan Castle", icon_castle_d|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (176.0,-47.0), [], 260.0),
("castle_31", "Vyincourd Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-65.7,-12.5), [], 260.0),
("castle_32", "Knudarr Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (2.0,30.1), [], 260.0),
("castle_33", "Etrosq Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-101.4,-32.1), [], 80.0),
("castle_34", "Hrus Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-72.5,78.6), [], 260.0),
("castle_35", "Haringoth Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-110.0,0.0), [], 260.0),
("castle_36", "Jelbegi Castle", icon_castle_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-47.3,53.2), [], 260.0),
("castle_37", "Dramug Castle", icon_castle_c|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (55.3,23.0), [], 260.0),
("castle_38", "Tulbuk Castle", icon_castle_d|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (141.7,33.3), [], 260.0),
("castle_39", "Slezkh Castle", icon_castle_snow_a|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (56.8,74.5), [], 280.0),
("castle_40", "Uhhun Castle", icon_castle_d|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (62.9,-26.0), [], 260.0),
("castle_41", "Jameyyed Castle", icon_castle_d|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (71.3,-71.1), [], 260.0),
("castle_42", "Teramma Castle", icon_castle_d|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (70.0,-96.0), [], 80.0),
("castle_43", "Sharwa Castle", icon_castle_d|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (172.0,-65.0), [], 260.0),
("castle_44", "Durrin Castle", icon_castle_d|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (128.0,-87.0), [], 260.0),
("castle_45", "Caraf Castle", icon_castle_d|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (30.6,-110.6), [], 260.0),
("castle_46", "Weyyah Castle", icon_castle_d|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (13.3,-84.4), [], 260.0),
("castle_47", "Samarra Castle", icon_castle_d|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (116.0,-74.0), [], 260.0),
("castle_48", "Bardaq Castle", icon_castle_d|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (157.0,-80.0), [], 260.0),
("village_1", "Yaragar", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-60.0,-9.5), [], 100.0),
("village_2", "Burglen", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-13.5,3.5), [], 110.0),
("village_3", "Azgad", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-97.4,36.0), [], 120.0),
("village_4", "Nomar", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-36.6,-13.2), [], 130.0),
("village_5", "Kulum", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-122.7,106.3), [], 170.0),
("village_6", "Emirin", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (5.5,-2.5), [], 100.0),
("village_7", "Amere", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (39.3,-5.25), [], 110.0),
("village_8", "Haen", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-49.7,74.0), [], 120.0),
("village_9", "Buvran", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-85.0,-75.35), [], 130.0),
("village_10", "Mechin", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (8.8,34.75), [], 170.0),
("village_11", "Dusturil", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (137.2,-36.5), [], 100.0),
("village_12", "Emer", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-45.8,-58.5), [], 110.0),
("village_13", "Nemeja", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-119.0,3.0), [], 120.0),
("village_14", "Sumbuja", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (40.0,52.0), [], 130.0),
("village_15", "Ryibelet", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-49.3,26.25), [], 170.0),
("village_16", "Shapeshte", icon_village_snow_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (74.0,86.8), [], 170.0),
("village_17", "Mazen", icon_village_snow_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (44.7,91.4), [], 35.0),
("village_18", "Ulburban", icon_village_snow_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (73.7,30.1), [], 170.0),
("village_19", "Hanun", icon_village_snow_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (152.3,53.5), [], 170.0),
("village_20", "Uslum", icon_village_snow_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (116.0,80.3), [], 170.0),
("village_21", "Bazeck", icon_village_snow_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (60.4,85.0), [], 100.0),
("village_22", "Shulus", icon_village_snow_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (125.4,64.0), [], 110.0),
("village_23", "Ilvia", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-133.3,-37.6), [], 120.0),
("village_24", "Ruldi", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-57.6,-73.0), [], 130.0),
("village_25", "Dashbigha", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (125.2,-8.0), [], 170.0),
("village_26", "Pagundur", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-58.5,-30.8), [], 170.0),
("village_27", "Glunmar", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-146.3,-16.6), [], 170.0),
("village_28", "Tash Kulun", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (95.0,-11.4), [], 170.0),
("village_29", "Buillin", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-90.6,110.9), [], 170.0),
("village_30", "Ruvar", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (29.2,114.3), [], 170.0),
("village_31", "Ambean", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-24.0,53.0), [], 100.0),
("village_32", "Tosdhar", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (8.3,14.5), [], 110.0),
("village_33", "Ruluns", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-59.0,10.6), [], 120.0),
("village_34", "Ehlerdah", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (34.15,-30.0), [], 130.0),
("village_35", "Fearichen", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (2.14,86.9), [], 170.0),
("village_36", "Jayek", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (17.4,100.7), [], 170.0),
("village_37", "Ada Kulun", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (164.4,26.0), [], 170.0),
("village_38", "Ibiran", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-42.8,11.25), [], 170.0),
("village_39", "Reveran", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-124.3,-29.5), [], 170.0),
("village_40", "Saren", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-12.0,-53.0), [], 170.0),
("village_41", "Dugan", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (175.0,-39.5), [], 100.0),
("village_42", "Dirigh Aban", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (115.4,21.6), [], 110.0),
("village_43", "Zagush", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (99.4,-21.3), [], 120.0),
("village_44", "Peshmi", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (51.8,-50.0), [], 130.0),
("village_45", "Bulugur", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (151.5,-3.0), [], 170.0),
("village_46", "Fedner", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-82.4,-48.8), [], 170.0),
("village_47", "Epeshe", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-101.2,-53.7), [], 170.0),
("village_48", "Veidar", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-103.0,15.3), [], 170.0),
("village_49", "Tismirr", icon_village_snow_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (90.8,60.5), [], 10.0),
("village_50", "Karindi", icon_village_snow_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (64.1,55.9), [], 170.0),
("village_51", "Jelbegi", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-40.0,62.0), [], 100.0),
("village_52", "Amashke", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (38.2,-67.7), [], 110.0),
("village_53", "Balanli", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-130.3,42.0), [], 120.0),
("village_54", "Chide", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-19.0,15.5), [], 130.0),
("village_55", "Tadsamesh", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (37.3,23.7), [], 170.0),
("village_56", "Fenada", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-5.55,75.5), [], 170.0),
("village_57", "Ushkuru", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (24.75,-7.7), [], 170.0),
("village_58", "Vezin", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (78.5,118.3), [], 170.0),
("village_59", "Dumar", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-101.0,-45.0), [], 170.0),
("village_60", "Tahlberl", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-26.6,30.0), [], 170.0),
("village_61", "Aldelen", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-99.8,85.65), [], 100.0),
("village_62", "Rebache", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (36.7,59.5), [], 100.0),
("village_63", "Rduna", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (70.75,1.6), [], 100.0),
("village_64", "Serindiar", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-41.5,-35.8), [], 100.0),
("village_65", "Iyindah", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-86.3,12.4), [], 100.0),
("village_66", "Fisdnar", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (109.0,127.5), [], 100.0),
("village_67", "Tebandra", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (65.0,23.0), [], 100.0),
("village_68", "Ibdeles", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-72.6,-97.5), [], 100.0),
("village_69", "Kwynn", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-26.5,77.6), [], 100.0),
("village_70", "Dirigsene", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-94.0,-27.0), [], 100.0),
("village_71", "Tshibtin", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-9.0,-20.0), [], 20.0),
("village_72", "Elberl", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-144.0,16.15), [], 60.0),
("village_73", "Chaeza", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-63.2,-51.4), [], 55.0),
("village_74", "Ayyike", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (49.0,31.0), [], 15.0),
("village_75", "Bhulaban", icon_village_snow_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (110.2,48.8), [], 10.0),
("village_76", "Kedelke", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (91.5,-34.8), [], 35.0),
("village_77", "Rizi", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-64.8,81.5), [], 160.0),
("village_78", "Sarimish", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-30.2,-53.3), [], 180.0),
("village_79", "Istiniar", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-134.1,-5.5), []),
("village_80", "Vayejeg", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-1.5,56.0), [], 40.0),
("village_81", "Odasan", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-17.2,123.6), [], 20.0),
("village_82", "Yalibe", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (12.0,-26.0), [], 60.0),
("village_83", "Gisim", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-79.9,55.2), [], 55.0),
("village_84", "Chelez", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-45.6,-83.0), [], 15.0),
("village_85", "Ismirala", icon_village_snow_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (22.8,71.7), [], 10.0),
("village_86", "Slezkh", icon_village_snow_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (60.5,68.2), [], 35.0),
("village_87", "Udiniad", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (52.3,111.8), [], 160.0),
("village_88", "Tulbuk", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (135.8,24.7), [], 180.0),
("village_89", "Uhhun", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (70.1,-27.9), []),
("village_90", "Jamiche", icon_village_a|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-12.7,-85.5), [], 40.0),
("village_91", "Ayn Assuadi", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (21.6,-95.3), [], 20.0),
("village_92", "Dhibbain", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (42.5,-111.6), [], 60.0),
("village_93", "Qalyut", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (50.0,-94.8), [], 55.0),
("village_94", "Mazigh", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (75.4,-61.65), [], 15.0),
("village_95", "Tamnuh", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (99.0,-90.5), [], 10.0),
("village_96", "Habba", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (107.0,-75.0), [], 35.0),
("village_97", "Sekhtem", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (82.3,-76.8), [], 160.0),
("village_98", "Mawiti", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (117.7,-62.2), [], 180.0),
("village_99", "Fishara", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (158.35,-98.0), []),
("village_100", "Iqbayl", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (150.0,-106.5), [], 40.0),
("village_101", "Uzgha", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (154.0,-69.5), [], 20.0),
("village_102", "Shibal Zumr", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (77.2,-91.0), [], 60.0),
("village_103", "Mijayet", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (121.0,-95.6), [], 55.0),
("village_104", "Tazjunat", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (159.0,-58.5), [], 15.0),
("village_105", "Aab", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (135.0,-88.5), [], 10.0),
("village_106", "Hawaha", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (10.3,-91.0), [], 35.0),
("village_107", "Unriya", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (156.6,-84.0), [], 160.0),
("village_108", "Mit Nun", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (28.8,-107.3), [], 180.0),
("village_109", "Tilimsal", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (53.0,-114.5), []),
("village_110", "Rushdigh", icon_village_c|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (38.0,-104.0), [], 40.0),
("salt_mine", "Salt Mine", icon_village_a|pf_disabled|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (14.2,-31.0), []),
("four_ways_inn", "Four Ways Inn", icon_village_a|pf_disabled|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (4.8,-39.6), []),
("test_scene", "test scene", icon_village_a|pf_disabled|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (10.8,-19.6), []),
("battlefields", "battlefields", icon_village_a|pf_disabled|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (10.8,-16.6), []),
("dhorak_keep", "Dhorak Keep", icon_town|pf_disabled|pf_is_static|pf_label_small|pf_always_visible|pf_no_label|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-50.0,-58.0), []),
("training_ground", "Training Ground", icon_training_ground|pf_disabled|pf_is_static|pf_label_small|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (3.0,-7.0), []),
("training_ground_1", "Training Field", icon_training_ground|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (37.4,102.8), [], 100.0),
("training_ground_2", "Training Field", icon_training_ground|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-12.8,33.0), [], 100.0),
("training_ground_3", "Training Field", icon_training_ground|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (70.5,72.0), [], 100.0),
("training_ground_4", "Training Field", icon_training_ground|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (11.5,-75.2), [], 100.0),
("training_ground_5", "Training Field", icon_training_ground|pf_is_static|pf_label_small|pf_label_medium|pf_always_visible|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-125.8,12.5), [], 100.0),
("bridge_1", "{!}1", icon_bridge_snow_a|pf_is_static|pf_label_small|pf_always_visible|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (39.37,65.1), []),
("bridge_2", "{!}2", icon_bridge_snow_a|pf_is_static|pf_label_small|pf_always_visible|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (56.44,77.88), [], 4.28),
("bridge_3", "{!}3", icon_bridge_snow_a|pf_is_static|pf_label_small|pf_always_visible|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (70.87,87.95), [], 64.5),
("bridge_4", "{!}4", icon_bridge_snow_a|pf_is_static|pf_label_small|pf_always_visible|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (93.71,62.13), []),
("bridge_5", "{!}5", icon_bridge_snow_a|pf_is_static|pf_label_small|pf_always_visible|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (11.02,72.61), [], 21.5),
("bridge_6", "{!}6", icon_bridge_b|pf_is_static|pf_label_small|pf_always_visible|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-8.83,52.24), []),
("bridge_7", "{!}7", icon_bridge_b|pf_is_static|pf_label_small|pf_always_visible|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-29.79,76.84), []),
("bridge_8", "{!}8", icon_bridge_b|pf_is_static|pf_label_small|pf_always_visible|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-64.05,-6.0), [], 1.72),
("bridge_9", "{!}9", icon_bridge_b|pf_is_static|pf_label_small|pf_always_visible|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-64.95,-9.6), []),
("bridge_10", "{!}10", icon_bridge_b|pf_is_static|pf_label_small|pf_always_visible|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-75.32,-75.27), []),
("bridge_11", "{!}11", icon_bridge_a|pf_is_static|pf_label_small|pf_always_visible|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-24.39,67.82), [], 81.3),
("bridge_12", "{!}12", icon_bridge_a|pf_is_static|pf_label_small|pf_always_visible|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-114.33,-1.94), []),
("bridge_13", "{!}13", icon_bridge_a|pf_is_static|pf_label_small|pf_always_visible|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-84.02,-7.0), []),
("bridge_14", "{!}14", icon_bridge_a|pf_is_static|pf_label_small|pf_always_visible|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-23.36,75.8), [], 66.6),
("looter_spawn_point", "{!}looter sp", pf_disabled|pf_is_static|pf_label_small, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (26.0,77.0), [(trp_looter,15,0),]),
("steppe_bandit_spawn_point", "the steppes", pf_disabled|pf_is_static|pf_label_small, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (125.0,9.0), [(trp_looter,15,0),]),
("taiga_bandit_spawn_point", "the tundra", pf_disabled|pf_is_static|pf_label_small, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (78.0,84.0), [(trp_looter,15,0),]),
("forest_bandit_spawn_point", "the forests", pf_disabled|pf_is_static|pf_label_small, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-35.0,18.0), [(trp_looter,15,0),]),
("mountain_bandit_spawn_point", "the highlands", pf_disabled|pf_is_static|pf_label_small, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-90.0,-26.8), [(trp_looter,15,0),]),
("sea_raider_spawn_point_1", "the coast", pf_disabled|pf_is_static|pf_label_small, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (48.5,110.0), [(trp_looter,15,0),]),
("sea_raider_spawn_point_2", "the coast", pf_disabled|pf_is_static|pf_label_small, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-42.0,76.7), [(trp_looter,15,0),]),
("desert_bandit_spawn_point", "the deserts", pf_disabled|pf_is_static|pf_label_small, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (110.0,-100.0), [(trp_looter,15,0),]),
("spawn_points_end", "{!}last spawn point", pf_disabled|pf_is_static|pf_label_small, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (0.0,0.0), [(trp_looter,15,0),]),
("reserved_1", "{!}last spawn point", pf_disabled|pf_is_static|pf_label_small, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (0.0,0.0), [(trp_looter,15,0),]),
("reserved_2", "{!}last spawn point", pf_disabled|pf_is_static|pf_label_small, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (0.0,0.0), [(trp_looter,15,0),]),
("reserved_3", "{!}last spawn point", pf_disabled|pf_is_static|pf_label_small, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (0.0,0.0), [(trp_looter,15,0),]),
("reserved_4", "{!}last spawn point", pf_disabled|pf_is_static|pf_label_small, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (0.0,0.0), [(trp_looter,15,0),]),
("reserved_5", "{!}last spawn point", pf_disabled|pf_is_static|pf_label_small, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (0.0,0.0), [(trp_looter,15,0),]),

] # PARTIES END
